### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#11]
- [ ] We should follow WAI guidelines for attaching proper labels to search results. For reference, [ReachUI](https://reach.tech/combobox/) and [React Aria Combobox](https://react-spectrum.adobe.com/react-aria/useComboBox.html)

**Comment by oliviertassinari** [comment]
If you are looking for more option/benchmark sources, you could also look at the headless version of MUI: [useAutocomplete](https://next.material-ui.com/components/autocomplete/#useAutocomplete).
