### ISSUE TITLE
Extra right margin is added when kbar is visible

### ISSUE THREAD

**Issue by ospfranco** [timc1/kbar#112]
Hey! First of all thanks a lot for the package

I'm not sure if I'm doing something wrong here, whenever the Kbar component is displayed a margin right is added to the documents body... that is messing up the padding in my page:

<img width="1338" alt="Screen Shot 2021-11-04 at 13 38 44" src="https://user-images.githubusercontent.com/1634213/140390970-2a20c102-feb8-4269-ae9a-29055f2becce.png">

I tracked it down to this piece of code:

https://github.com/timc1/kbar/blob/dde8f0e3c485b1382f59b3bf7b6636da6d3ff6f0/src/InternalEvents.tsx#L119

But it doesn't look like there is any way to disable this?

**Comment by timc1** [comment]
Hey @ospfranco! The margin is added to ensure we prevent the UI from shifting due to the visibility of the scrollbar: https://github.com/timc1/kbar/pull/90.

Can you link a screen recording of the behavior you are seeing?

**Comment by kxxoling** [comment]
@timc1 A `margin-right: 15px` is added to body at the moment kbar is shown.

**Comment by ospfranco** [comment]
Yeah, there is not much to it, the body is shifted because margin-right: 15px is added to it, maybe it makes sense on certain layouts (where the body is scrollable) but in my case, a sub-div is scrollable and it just moves the entire screen

**Comment by nghieptiki** [comment]
Issue is till in `0.1.0-beta.24`

https://user-images.githubusercontent.com/54924428/147554654-39a409da-30f0-4a6c-b30d-87c6b2e05b9b.mov

**Comment by timc1** [comment]
@nghieptiki are you rendering that table inside an iframe?

**Comment by nghieptiki** [comment]
@timc1 the issue with any container can be scrollable

https://user-images.githubusercontent.com/54924428/147626900-8cdab664-0d17-45f4-9784-63a4b6708b0b.mp4
