### ISSUE TITLE
Open `kbar` programmatically

### ISSUE THREAD

**Issue by mirshko** [timc1/kbar#118]
Is it possible to open the `kbar` programmatically to have a button the user can press to open it? 

Just to help with showing how a user can access this, couldn't find in the docs if this is possible.

**Comment by timc1** [comment]
Hey @mirshko, you can toggle `kbar` programmatically using `toggle`, which can be accessed by `useKBar`:

```
const { query } = useKBar();

query.toggle()
```

**Comment by mirshko** [comment]
Amazing thank you! :D
