### ISSUE TITLE
Dynamic action based on current query value

### ISSUE THREAD

**Issue by leeoocca** [timc1/kbar#119]
Hi Tim, thank you so much for your work on this awesome library!

I wanted to ask you if it's possible, as of the current implementation, to have an action dynamically change based on the value of the current query.

Thanks a lot, keep up the good work!

**Comment by timc1** [comment]
Hey @leeoocca! Thanks for the comment :-)

Do you have a specific example/use case for this?

**Comment by leeoocca** [comment]
Sure! I had in mind to add an example but then I probably forgot.

My application has a dynamic page (`/users/:login`) which shows users' profiles depending on the unique _login_ it finds in the URI. It would be very cool to be able to access directly a users' profile page from <kbd>kbar</kbd>.

Say you enter the _Users_ parent action, then start typing the user's login. On enter you would be redirected to `/users/${query.value}`. Another action could redirect you to a search page (`/search?q=${query.value}`).

Another use case could be dynamically adding suggestions. After you type the first couple characters, an API call could show a couple user logins matching your query directly inside <kbd>kbar</kbd>.

What do you think?

**Comment by timc1** [comment]
> Another use case could be dynamically adding suggestions. After you type the first couple characters, an API call could show a couple user logins matching your query directly inside

This can be done by using some internal state alongside `useRegisterActions`:


```
const { query } = useKBar(state => ({ query: state.query });
const [users, setUsers] = useState([]);

useEffect(() => {
  fetchUsers(query).then(setUsers)
}, [query])

useRegisterActions(users.map(user => createAction(...), [users]);
```

Can optimize this, but the gist is to fetch users based on the search query; once loaded, generate actions for each user and register them in kbar.

**Comment by leeoocca** [comment]
I see. This looks good, I'll try to implement it right away.

> Say you enter the Users parent action, then start typing the user's login. On enter you would be redirected to /users/${query.value}. Another action could redirect you to a search page (/search?q=${query.value}).

Do you feel like this logic is light enough for the simple usage I mentioned earlier?

**Comment by leeoocca** [comment]
I'm getting, from the compiler:

```ts
TypeError: getState is not a function

> 42 | 	const { query } = useKBar((state) => ({ query: state.query }));
     | 	                          ^
```

...from the IDE:

```
Property 'query' does not exist on type 'KBarState'. ts(2339)
```

My code for the simpler use case:

```tsx
const { query } = useKBar((state) => ({ query: state.query }));
const [user, setUser] = useState("");

useEffect(() => {
	setUser(query);
}, [query]);

const userSearch: BaseAction[] = [
	{
		id: "userSearch",
		name: query,
		perform: () => Router.push(`/users/${query}`),
	},
];

useRegisterActions(userSearch, [user]);
```

**Comment by timc1** [comment]
Apologies, `query` comes directly from `useKbar`: `const { query } = useKBar()`

**Comment by timc1** [comment]
> Do you feel like this logic is light enough for the simple usage I mentioned earlier?

You'll probably want to add some type of debounce if you will be hitting some external API. Shoot me what you've got and I can help :-)

**Comment by leeoocca** [comment]
> Apologies, `query` comes directly from `useKbar`: `const { query } = useKBar()`

Sorry, I can't find the string value in the `query` object you get from `useKBar`. Maybe I have to call a specific function?

> You'll probably want to add some type of debounce if you will be hitting some external API.

I was actually talking about the simpler use case where you don't need to hit an API, but the `perform` funcion just redirects you to the user page (`/users/${query.value}`).

**Comment by timc1** [comment]
> Sorry, I can't find the string value in the `query` object you get from `useKBar`. Maybe I have to call a specific function?
> 

https://github.com/timc1/kbar/issues/119#issuecomment-973111624

**Comment by leeoocca** [comment]
Still getting that TypeError from https://github.com/timc1/kbar/issues/119#issuecomment-973104612 😕

**Comment by timc1** [comment]
You are rendering this hook in a component within the `KBarProvider`, yes?

**Comment by leeoocca** [comment]
No, sorry, my bad. I moved it to a lower order component and now it's not throwing the type error.

Unfortunately `query` is of type `KBarQuery`. I still can't access the current value.

**Comment by timc1** [comment]
Please refer to https://github.com/timc1/kbar/issues/119#issuecomment-973111624 – I suggest digging into the [source](https://github.com/timc1/kbar/tree/main/src) to get a feel for how to use the provided APIs; see how `useKBar` is used elsewhere, etc.

**Comment by leeoocca** [comment]
Ok, thanks again a lot, I'll have a look. I may have undestood the problem.

**Comment by leeoocca** [comment]
Yes, the problem was that `query` was overwritten by the default `useKBar` return. Renaming the variable to `queryValue` solved the problem.

```ts
const router = useRouter();

const { queryValue } = useKBar((state) => ({ queryValue: state.searchQuery }));
const [user, setUser] = useState("");

useEffect(() => { setUser(queryValue); }, [queryValue]);

const userSearch: BaseAction[] = [
	{
		id: "userSearch",
		name: queryValue.length
			? `Go to ${queryValue}'s profile`
			: "Start typing an user's login",
		parent: "users",
		perform: () =>
			router.push(
				queryValue.length ? `/users/${queryValue}` : "/users"
			),
	},
];
```
