### ISSUE TITLE
Support more complex shortcuts

### ISSUE THREAD

**Issue by avigoldman** [timc1/kbar#121]
Similar to #55, it'd be great to have more powerful config for the shortcuts. 

For example, I'd love to have a shortcut registered for <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>

**Comment by timc1** [comment]
Hey @avigoldman! Can something like this be implemented with what we currently have? E.g. cold+shift+I is just cmd+I (capital i), and the user can transform that if needed?

**Comment by baptisteArno** [comment]
Hey guys, is it currently possible to have a shortcut bound to `cmd + z`?

This seems not to work:
```ts
useRegisterActions(
    [
      {
        id: 'undo',
        name: 'Undo',
        shortcut: ['cmd', 'z'],
        perform: async () => {
          ...
        },
      },
    ]
  )
```

**Comment by timc1** [comment]
Hey @baptisteArno! <kbd>cmd</kbd>+<kbd>z</kbd> is bound by our [internal history manager](https://github.com/timc1/kbar/blob/805b6ad442124a3ab9ed4c4c1292ac8ce4c50a8d/src/action/HistoryImpl.ts#L43-L47). Is your use case simply to display `undo`/`redo` as clickable actions? If that is the case, you can do so without adding the `shortcut` property to that action you have above.

**Comment by baptisteArno** [comment]
So no way to have my action triggered on cmd + z?

And what about cmd + s? It seems to not work as well

**Comment by timc1** [comment]
Hm, cmd+z triggers undo that is managed within kbar. If I'm understanding correctly, you want to `undo` a functionality _outside_ of kbar, right?

> And what about cmd + s? It seems to not work as well

We [explicitly ignore](https://github.com/timc1/kbar/blob/main/src/InternalEvents.tsx#L161) triggering shortcuts that use the `meta` key, something that we should probably revisit. Originally it was there to prevent overriding our base cmd+k. So for now we can't, but adding [here](https://github.com/timc1/kbar/issues/166).

**Comment by baptisteArno** [comment]
Thanks! Yeah, I'm building a form builder and it would be nice to have these shortcuts: cmd + z to undo form modifications, cmd + shift + z to redo them and cmd + s to save the form.

I can implement them elsewhere, but it would be neat to instantiate it directly with kbar 👍
