### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length') in beta.23

### ISSUE THREAD

**Issue by elonglau** [timc1/kbar#132]
Usecase like this:
```
<KBarProvider actions={[]} options={CommandBarOptions}>
// app code
<KBarProvider>
```

Error message like:
```
TypeError: Cannot read properties of undefined (reading 'length')
at...useState
at KNgM.i.KBarProvider
```

This error ocured in new versions, but when i back to the use beta.21, this error disappeared.
I think the new version change some apis, so it cannot compatible the old "actions" type.

by the way, this package is referenced in outline app.

**Comment by timc1** [comment]
Hey @elonglau! Are you able to share some additional details so we can dig into the issue? Off the top of my mind, what does the stack trace look like when you expand that `TypeError`?
