### ISSUE TITLE
Outdated state in `perform`

### ISSUE THREAD

**Issue by maxsteenbergen** [timc1/kbar#133]
Hi,

This is most likely ignorance on my part, but I couldn't find any stand out example on the docs so forgive me if this is not an appropriate question. Basically I'm simply trying to flip a boolean in one of my component's state. However, I think that useRegisterActions is memoized or something similar, since KBar actions don't seem to register changes in state?

What's the proper pattern to use here?

The gist of my code is the following: 

````
const [Expanded, setExpanded] = useState(false)
useRegisterActions([
  {
    id: "expandSidebar",
    name: "Expand Sidebar",
    section: "Shell",
    keywords: "expand collapse sidebar",
    perform: ()=> { setExpanded( !Expanded )} // ← This only records the initial value of the Expanded state, so only works once
  }
])
````

**Comment by timc1** [comment]
Hey! You can solve this by passing a callback into setExpanded such that:

```() => setExpanded(expanded => !expanded)```

**Comment by maxsteenbergen** [comment]
@timc1 Thanks! That totally did the trick! Closing this and thank you for an amazing project
