### ISSUE TITLE
[Question] how to trigger the kbar manually

### ISSUE THREAD

**Issue by chasoft** [timc1/kbar#135]
Hello,

The default behavior for a user to show/activate the kbar is to press "ctrl+k" but I want to provide more ways, such as to click a SearchIcon and kbar will be showed. How to get this behavior?

Thank you!

**Comment by chasoft** [comment]
Playing with KBarSearch, solved by creating a custom component.

**Comment by chasoft** [comment]
My custom component just solved 50% of my purpose. 

I still want an exported function to trigger the search box...  how to get this behavior? Thank you!

eg: user clicks the SearchIcon button!
![Untitled](https://user-images.githubusercontent.com/7332422/145004127-4068716e-572c-4fd9-87f9-ed0a7fcbc27a.png)

**Comment by razzeee** [comment]
The way to do this seems to be to use `query.toggle` like here https://github.com/timc1/kbar/blob/8ce425ff84242daaba39633f18203326168b39cb/example/src/Layout.tsx#L15
