### ISSUE TITLE
Add zIndex to Positioner

### ISSUE THREAD

**Issue by Davidpallison** [timc1/kbar#137]
`const defaultStyle: React.CSSProperties = {
  position: "fixed",
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "center",
  width: "100%",
  inset: "0px",
  padding: "14vh 16px 16px",
  zIndex:999,
};`

**Comment by timc1** [comment]
Hey David! Users can extend `KBarPositioner` and do so themselves – additionally, arbitrary z-indexes are something we'd like to avoid 😉
