### ISSUE TITLE
Shortcuts seem to be broken

### ISSUE THREAD

**Issue by bragur** [timc1/kbar#140]
Running the newest build on vercel [#fd73c15](https://github.com/timc1/kbar/commit/fd73c15ffe25a9a8e8846ac25c142f5783fc4d12) the shortcuts don't seem to do anything. Hitting `?` just adds `?` to the input box and does not bring up a shortcut to the docs.

**Comment by timc1** [comment]
Hey @bragur! You're going to need to press `?` when the commandbar is closed.

**Comment by bragur** [comment]
Oh gosh 😅🙈
