### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'registerActions')

### ISSUE THREAD

**Issue by toughyear** [timc1/kbar#141]
I am trying to use the Kbar behind a feature flag. When. I turn off the feature and turn it on again, I get the following error on the first load. 

```bash
TypeError: Cannot read properties of undefined (reading 'registerActions')
```

On the next refresh, it doesn't crash the app. 

Here is the error stack - 
```bash

(anonymous function)
node_modules/kbar/lib/useRegisterActions.js:34
  31 | if (!actionsCache.length) {
  32 |     return;
  33 | }
> 34 | var unregister = query.registerActions(actionsCache);
     | ^  35 | return function () {
  36 |     unregister();
  37 | };
View compiled
invokePassiveEffectCreate
node_modules/react-dom/cjs/react-dom.development.js:23487
  23484 | 
  23485 | function invokePassiveEffectCreate(effect) {
  23486 |   var create = effect.create;
> 23487 |   effect.destroy = create();
  23488 | }
  23489 | 
  23490 | function flushPassiveEffectsImpl() {
View compiled
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:3945
  3942 | function callCallback() {
  3943 |   didCall = true;
  3944 |   restoreAfterDispatch();
> 3945 |   func.apply(context, funcArgs);
       | ^  3946 |   didError = false;
  3947 | } // Create a global error event handler. We use this to capture the value
  3948 | // that was thrown. It's possible that this error handler will fire more
View compiled

```

This might be caused because when I am adding dynamic actions based on the feature flag, it is not able to find the KbarProvider for the first time the feature is enabled.

Is there a better to integrate Kbar with a feature flag? I don't just want to disable or hide the cmd+k menu but also the shortcuts. A boolean value to disable kbar would be helpful.

**Comment by toughyear** [comment]
Currently, found a workaround for this - 
```typescript
  const { query } = useKBar();

  if (isFeatureEnabled && query) {
// call dynamic actions 
// useRegisterActions(...
```

I am checking if the Kbar query is undefined or not before I start adding dynamic actions. However, a better way would be to actually wait for KBarContext to populate instead of throwing an error.

**Comment by timc1** [comment]
Hey @toughyear! If I'm seeing the above correctly, it looks like `useRegisterActions` is called conditionally based on the feature flag, which goes against the [rules of hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level). If you have a set of actions that you would like to disable based on flag, you can dynamically generate the actions, and pass the actions as part of `useRegisterActions`'s dependencies list:

```tsx
const actions = React.useMemo(() => [...], [myFeatureFlag]);

useRegisterActions(actions, [actions]);
```

**Comment by toughyear** [comment]
Thanks for the quick response @timc1. I tried implementing your solution but I still get the error because useRegisterActions looks for the KBar to add the action to which is not there. For now, I am relying on the workaround.

**Comment by timc1** [comment]
So you're trying to add actions based on the current query – your logic can be placed within `useRegisterActions`. Unless you are calling `useRegisterActions` outside where you place `KBarProvider`, `query` should never be undefined.

```tsx
useRegisterActions(!query ? [] : [...], [isFeatureEnabled, query])
```

**Comment by timc1** [comment]
Closing this issue but happy to debug further :-)
