### ISSUE TITLE
Should search results allow combinations of name + keywords?

### ISSUE THREAD

**Issue by smhutch** [timc1/kbar#142]
I have a command like this:

```tsx
[
  { name: 'Add new', keywords: 'create', ...otherStuff }
]
```

But I found that searching for "Create new" would not return this item. Searcing for "new" or "create" alone would work, but not when my search query is mixed between the two it wouldn't work.

For now I can work around this by duplicating the entire name inside the keywords, but it would be nice to not need to think about this 😄

**Comment by timc1** [comment]
This _should_ in theory work as we [match against both the name and keywords](https://github.com/timc1/kbar/blob/fd73c15ffe25a9a8e8846ac25c142f5783fc4d12/src/useMatches.tsx#L112). It may be that `match-sorter` views each key's values distinct. 

Typically we're going to be dynamically generating actions, so it is easy enough to push an action's `name` to the `keywords`.
