### ISSUE TITLE
Consider including the section name in the results logic

### ISSUE THREAD

**Issue by smhutch** [timc1/kbar#143]
In my case I have a bunch of commands, all nested under a section (let's call that section "Projects").

I would love to be able to search for "add project", and it return all items inside this section. Do you think that's generally desired behaviour?

For now I work around this by adding the section name inside the keywords for each item.

**Comment by timc1** [comment]
Same as https://github.com/timc1/kbar/issues/142#issuecomment-999767276, however we can make this default behavior by adding the parent's name as part of an action's keywords [here](https://github.com/timc1/kbar/blob/main/src/action/ActionImpl.ts#L48).
