### ISSUE TITLE
Pass search value to action

### ISSUE THREAD

**Issue by josiahwiebe** [timc1/kbar#145]
First of all, thank you for this great project!

I'm wondering if it's possible to pass the text from the search bar to the action. For example, let's say I want to create an action that allows the user to open up a nested action, then input an email address and perform the action based on that input. 

Any current way to implement something like this?

**Comment by timc1** [comment]
Hey @josiahwiebe! You _can_ do some dynamic work to enable rendering an action based on the search query; however, this is a workaround and we should create an API within the lib that makes this work trivial – we can continue the convo here https://github.com/timc1/kbar/issues/147 :-)

```tsx
import { createAction, useKBar, useRegisterActions } from "../../../src";

const login = createAction({
  name: "Login with email",
});

export default function useAuthActions() {
  const { search } = useKBar((state) => ({
    search: state.searchQuery,
  }));

  useRegisterActions(
    [
      login,
      createAction({
        name: `Send login link to ${search}`,
        parent: login.id,
        perform: () => {
          // Send login link
        },
      }),
    ],
    [search]
  );
}
```

**Comment by josiahwiebe** [comment]
Thanks @timc1! I hacked it together to work like this, but a fully featured API would be top notch.
