### ISSUE TITLE
Support async actions, loading states

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#147]
Related #145.

Leaving this for thought, will continue post holidays:

It would be really great to support an even more flexible UI for async actions.

Imagine if we wanted to have an action, `Login`, where once performed, opens up a set of nested actions, `Continue with email` being one of the options. Performing `Continue with email` opens up a single nested action, `Send login link`. `Send login link` will take the current search query and send an API request to send an login link to the email provided.

Let's break this down into a few key requirements:

- Our current `useMatches` returns nested searches automatically. We may want to display nested searches, but maybe we won't want to display specific nested actions as the UX for stepping through this login flow would be good. Maybe.
- When a command is performed, we [immediately toggle](https://github.com/timc1/kbar/blob/fd73c15ffe25a9a8e8846ac25c142f5783fc4d12/src/KBarResults.tsx#L115) kbar. How can we invert the control a bit here to allow users to specify _when_ they want to trigger the toggle?
- Supporting async actions will require us to create an API where developers can trigger states within each action. How can we display a loading state for a single action?
- What is a proper API where we can **bold** the `timchang@hey.com` text in an action below so users can easily create dynamic UIs?

<img width="1436" alt="Screen Shot 2021-12-25 at 4 07 56 PM" src="https://user-images.githubusercontent.com/12195101/147395831-4785be7d-e539-48c7-b710-a9af043e4bb3.png">

**Comment by riccardocalligaro** [comment]
hello, any news on this? 
this would be a great feature. thanks

**Comment by EmirBoyaci** [comment]
I'm also looking for that
