### ISSUE TITLE
Enable custom placeholder in `KBarSearch`

### ISSUE THREAD

**Issue by DavideCarvalho** [timc1/kbar#149]
When there is no action being performed, the default placeholder is ```"Type a command or search…"```, but we'd like to use a custom placeholder

**Comment by timc1** [comment]
Hey @DavideCarvalho nice call – we should probably support that within `KbarSearch`. For your purpose right now, you can just pass a custom `placeholder` to the search component which will override the default:

```tsx
const {
  currentRootActionId,
  actions
} = useKBar((state) => ({
  currentRootActionId: state.currentRootActionId,
  actions: state.actions,
));

const placeholder = React.useMemo(
    () =>
      currentRootActionId
        ? actions[currentRootActionId].name
        : "Type a command or search…",
    [actions, currentRootActionId]
  );

// ...
<KBarSearch 
  placeholder={placeholder}
/>
```

**Comment by BigOsvaap** [comment]
I would like to work on this, I was thinking in to change the code to add a new property called placeholderText

https://github.com/timc1/kbar/blob/a232f3d8976a61eeeb844152dea25a23a76ad368/src/KBarSearch.tsx#L8-L10

```Javascript
 export function KBarSearch( 
    props: React.InputHTMLAttributes<HTMLInputElement>,
    placeholderText?: string | undefined 
  ) { 
```

and in the placeholder part

https://github.com/timc1/kbar/blob/bb2cf52e0bdc7a68f59a7eda7f7017f85b54f090/src/KBarSearch.tsx#L35-L41

for something like this
```Javascript
const placeholder = React.useMemo( 
   () => {
    const text = placeholderText 
        ? placeholderText
        : "Type a command or search…"
    return currentRootActionId 
        ? actions[currentRootActionId].name 
        : text
   }, [actions, currentRootActionId] 
 );
```

@timc1 
Let me know if that looks good, so I can make a PR if you're ok

**Comment by timc1** [comment]
@BigOsvaap that sounds reasonable – probably use `defaultPlaceholder` and we'll be good to go. 💯

**Comment by timc1** [comment]
@kirillrogovoy will be in the next release! https://github.com/timc1/kbar/commit/3d1c4c7451d37ff15313b58e9b6689f6cd0fd887
