### ISSUE TITLE
Can't run a local dev build

### ISSUE THREAD

**Issue by xtabbas** [timc1/kbar#15]
Getting multiple can't resolves like this

```
ERROR in ./example/src/index.tsx 2:0-35 Module not found: Error: Can't resolve 'react-dom' in '/.../kbar-main/example/src'

ERROR in ./example/src/index.tsx 4:0-59 Module not found: Error: Can't resolve 'react-router-dom' in '/.../kbar- main/example/src'

ERROR in ./src/InternalKeyboardEvents.tsx 1:0-31 Module not found: Error: Can't resolve 'react' in '/.../kbar-main/src' 
@ ./src/KBarContextProvider.tsx 3:0-62 9:41-63 
@ ./example/src/App.tsx 23:0-61 42:45-57 
@ ./example/src/index.tsx 3:0-24 5:153-156
```

Do you know what might be happening?

**Comment by driaug** [comment]
This is because of the use of NPM peer dependencies,
Peer dependencies have been deprecated with NPM 3.x and are no longer automatically installed. 

Truly something for @timc1 to decide but it would be better to step off those and add them as dev dependencies! 
Much love ♥

**Comment by xtabbas** [comment]
Hey! Thanks a lot, I was able to build the app, but it's not serving it on any port. Rather (it looks like its) copying the files in the example/src/. What is the appropriate way of running locally? Much appreciated.

Why can't we just run it normally?

**Comment by driaug** [comment]
Not entirely sure, I'm trying to get it running locally as well. Will keep you posted if I get it fixed!

**Comment by timc1** [comment]
Hey @xtabbas @driau! How did you both start the dev server? A simple `npm install` followed by an `npm run dev` should get the example app running on port 8080 – you can build and work against the example app.

**Comment by driaug** [comment]
The result for me when I run `npm install` followed by `npm run dev`
![image](https://user-images.githubusercontent.com/31651090/133247264-829918b7-0722-41ba-9b19-c8ba339769ba.png)

**Comment by driaug** [comment]
Removing the peer dependencies to dev dependencies fixes the issue for me. Which version of NPM are you running?
