### ISSUE TITLE
Why does useKBar return undefined for query?

### ISSUE THREAD

**Issue by Jped** [timc1/kbar#151]
Hey,
 I am trying to toggle the KBar serach menu on a click and have seen it done in the [example here ](https://github.com/timc1/kbar/blob/16ae432abb832324387ad90ae23dcefbcb9c42e3/example/src/Layout.tsx#L15).

However whenever I try this line:
`const { query } = useKBar();`

I get that query is undefined.

What am I doing wrong?

**Comment by timc1** [comment]
Hey @Jped, have you made sure that the component which you are calling `useKBar` is rendered within a `KBarProvider`?

**Comment by Jped** [comment]
Yup that was the issue.

Thanks
