### ISSUE TITLE
How to combine with user defined shortcuts

### ISSUE THREAD

**Issue by ospfranco** [timc1/kbar#154]
I have a custom keyboard shortcut handler on parts of my app:

```ts
import { useWindowEvent } from "./useWindowEvent"

export function useKeyboardShortcut(key: string, callback: () => void, metaKey?: boolean) {
  useWindowEvent("keydown", (event) => {
    const activeElem = document.activeElement

    if (
      event.key === key &&
      event.metaKey === !!metaKey &&
      activeElem?.getAttribute("role") !== "menu" &&
      activeElem?.tagName !== "INPUT" &&
      activeElem?.tagName !== "TEXTAREA"
    ) {
      event.preventDefault()
      event.stopPropagation()
      callback()
    }
  })
}
```

Most of the time this works fine, except when I want to access the kbar shortcut instead of my shortcut, so for example I have a navigation shortcut `g + r` on kbar, then if I have a custom shortcut on my component for `r`, the kbar shortcut might be triggered but also the shortcut in my component

Any good idea to make both work? maybe the `useKbar` shortcut holds some state property I could use to not trigger my custom shortcuts?

**Comment by timc1** [comment]
Hey @ospfranco apologies for the later response – can you early return within `useWindowEvent` if the event's default has been prevented?:

```
  useWindowEvent("keydown", event => {
    if (event.defaultPrevented) return;
 
    // const activeElem...
  })
```

**Comment by ospfranco** [comment]
thanks @timc1 , I'll give it a try, but this might not solve the issue, it seemed that the behavior was non-deterministic, meaning sometimes my custom shortcut would fire first and sometimes kbar shortcut would fire first, then checking for the prevented flag might not always yield the expected result

**Comment by timc1** [comment]
Let's get an understanding of why it's firing in arbitrary order before tackling this – events _should_ be firing in the same order, so figuring that out will give us a good idea on how to approach a solution

**Comment by schickling** [comment]
@ospfranco did using `useWindowEvent` solve your problem?

**Comment by ospfranco** [comment]
unfortunately, I left the project where I was using kbar, so I didn't get to try it out, I just replaced my shortcut with a shift modifier in my local component.
