### ISSUE TITLE
Accessing the KBar active state

### ISSUE THREAD

**Issue by Christian-Garrison** [timc1/kbar#155]
## Use Case
- Current use case of the KBar is to provide an easy cmd + k interface to insert algolia search into. I am looking to add a FocusTrap via react-focus-trap which needs a boolean state

## Issue
- I do not know how to properly access the active state of the KBar

**Comment by timc1** [comment]
> I do not know how to properly access the active state of the KBar

You can access all visual states by collecting the value in `useKBar()`. Something like so will return the visibiliy:

```
const { showing } = useKBar((state) => ({
  showing: state.visualState !== VisualState.hidden,
}));
```

**Comment by Christian-Garrison** [comment]
@timc1 

When using 'useKBar' I am getting an error on `./node_modules/kbar/lib/useKBar.js:38` saying that "getState is not a function"

<img width="592" alt="Screen Shot 2022-01-18 at 8 55 29 AM" src="https://user-images.githubusercontent.com/75394049/149961135-af22fc97-c1eb-45cb-bd95-e59a72f7bc34.png">

Runtime Environment:
- "kbar": "^0.1.0-beta.25"
- Gatsby with TypeScript

**Comment by Christian-Garrison** [comment]
@timc1 Yes, currently using KBar as a component that is within Gatsby's wrapRootElement in `gatsby-browser.js`.

Below is what that component looks like
![carbon](https://user-images.githubusercontent.com/75394049/149963992-03f33101-7977-4e08-9452-26b9e060a6d1.png)

**Comment by Christian-Garrison** [comment]
@timc1 Or I guess no I am not, I see what you mentioned.
