### ISSUE TITLE
Add option to disable useDocumentLock in InternalEvents

### ISSUE THREAD

**Issue by Merlin04** [timc1/kbar#158]
In my application I've integrated kbar with [MUI](https://mui.com), and part of that involved replacing kbar's `KBarPortal` component with the MUI `Modal` plus [a wrapper to handle transition states correctly](https://github.com/kobra-dev/Kobra/blob/kbar/src/components/kbar/MuiModalPortal.tsx). However, MUI's `Modal` component implements kbar's document lock functionality by itself (in a way that works better with other MUI components), so kbar's implementation of this conflicts with MUI and causes some weird states of the page not being fully unlocked. In my app I've solved this by [patching out the `useDocumentLock` function in `InternalEvents.tsx`](https://github.com/kobra-dev/Kobra/blob/kbar/src/components/kbar/InternalEvents_patched.tsx) but this is quite janky and it would be great if there was an official way to disable it (similar to the `disableScrollbarManagement` option).

I'd be happy to write a PR to implement this, but I thought I should check to see if you thought that would be a good idea first.

**Comment by Merlin04** [comment]
Ended up deciding to go ahead and write a PR for this

**Comment by timc1** [comment]
Closed via #160
