### ISSUE TITLE
Babel wants an additional loader (React 18)

### ISSUE THREAD

**Issue by michaltakac** [timc1/kbar#16]
Hi, I'm trying `kbar` in my app (created with `create-react-app` where I use React 18 (`18.0.0-alpha-cb8a50619-20210909`) and I get this error when starting the app:

```
Failed to compile.

./node_modules/kbar/lib/useStore.js 120:10
Module parse failed: Unexpected token (120:10)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
| class Publisher {
>   getState;
|   subscribers = [];
|
```

In my App.js I have:

```
const actions = [
  {
    id: "blog",
    name: "Blog",
    shortcut: ["b"],
    keywords: "writing words",
    perform: () => (window.location.pathname = "blog"),
  },
  {
    id: "contact",
    name: "Contact",
    shortcut: ["c"],
    keywords: "email",
    perform: () => (window.location.pathname = "contact"),
  },
];

export default function App() {
  return (
    <KBarProvider actions={actions}>
        <App />
    </KBarProvider>
  );
}
```

EDIT: Seem like the importing of anything from `import { ... } from "kbar";` is crashing the app.

**Comment by tommoor** [comment]
I think we just need to set `esbuild` to a slightly older target. For a lib it makes sense to be a bit more conservative with which newer language features get compiled away.

**Comment by timc1** [comment]
We can actually remove that `esbuild.mjs` file as I had opted to use `esbuild-loader` in the webpack config – it defaults to `es2015` so we _should_ be ok there if I'm not mistaken

**Comment by TaylorFacen** [comment]
Hi, I'm running into this issue too. Is there a solution?

**Comment by timc1** [comment]
Hey @michaltakac, @TaylorFacen – can you give the [latest release](https://github.com/timc1/kbar/releases/tag/0.1.0-beta.5) a spin? Lowered the target to `es5` which should do the trick here.

**Comment by TaylorFacen** [comment]
It works! Thanks so much!
