### ISSUE TITLE
Update the docs to show `Ctrl + K` shortcut for non-mac users

### ISSUE THREAD

**Issue by smhutch** [timc1/kbar#161]
Some feedback from others on my team:

![CleanShot 2022-01-18 at 09 40 11](https://user-images.githubusercontent.com/7217244/149911566-64ee8444-f623-4fa7-95a2-6eb03dbb070c.png)

**Comment by timc1** [comment]
👉  https://github.com/timc1/kbar/commit/9dd99ec169d31f884bc1c8823bb49a86443b8bfb
