### ISSUE TITLE
Showcase projects using Kbar

### ISSUE THREAD

**Issue by lavgup** [timc1/kbar#162]
It would be great to have a showcase section on the README to highlight projects using Kbar. It would serve as a nice deal for inspiration as command palettes are relatively under-adopted and can be difficult to implement correctly.

Something like [this section](https://github.com/Phineas/lanyard#used-by) on Lanyard's README.

**Comment by timc1** [comment]
Great idea! 💯

**Comment by lavgup** [comment]
I'd be happy to introduce the section with a new PR.

Though, from the contributing section on the README, it looks like you wouldn't want so many individual PRs to add projects.

I think an ideal solution would be to have an issue (or GitHub Discussion) for users to be able to comment their project links on and then added to the README periodically (every x.x release etc.)

**Comment by timc1** [comment]
I've got a list of some projects in use that I need to filter out this weekend – keep an eye out! :-)

**Comment by timc1** [comment]
@lavgup https://github.com/timc1/kbar#used-by 💯
