### ISSUE TITLE
Interaction with commands that rely on body pointer-events

### ISSUE THREAD

**Issue by gsimone** [timc1/kbar#165]
Hello 👋 we came across an interesting problem integrating kbar with a radix-dialog component.
The problem comes from the order of operations when performing a command in kbar that relies on pointer-events state.

In the [reproduction here](https://codesandbox.io/s/radix-kbar-interaction-problem-lzi25):

- open kbar
- execute the command
- close the dialog (by clicking on the x or somewhere outside)
- verify that pointer events aren't working by trying to click the button

In our example, we have a radix-dialog opening via a kbar command. Radix stores the initial pointer-events value of the body and restores it when no more interaction-blocking elements are mounted [link to the code](https://github.com/radix-ui/primitives/blob/main/packages/react/use-body-pointer-events/src/useBodyPointerEvents.tsx#L38). 

This means that at `perform` time, radix will save the pointer-events none set by kbar - which is then immediately removed AFTER the command is performed and the VisualState is hidden. [link to the suspect kbar code](https://github.com/timc1/kbar/blob/47a01f61ec23883aafb183f48346bbbd5b745264/src/InternalEvents.tsx#L133)

Ideally, when a command is performed, the pointer-events would be back to the original body value, so:

```
# ideal order
- summon kbar
- user selects a command
- pointer events is restored
- command is performed
```

This way the command would be performed on the cleaned up version of the body and should fix the problem.

Note that we made a temp fix for this by just delaying our setState with a timeout that is enough so that kbar goes back in visually hidden state.

Thank you for reading and for the amazing lib ✌️

**Comment by timc1** [comment]
Fixed as part of https://github.com/timc1/kbar/commit/0f84f3463a9105539ff848cace6b12eee0aa150b – thanks for the heads up! :-)
