### ISSUE TITLE
Support shortcuts using meta key

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#166]
Related #166.

We currently ignore meta key strokes in our internal event handler. This was originally added as a quick workaround to prevent overriding base cmd+k functionality. Let's revisit this as shortcuts such as cmd+s to save a doc is common.

**Comment by maferland** [comment]
@timc1 Would love to be able to use `cmd+[any key that is not k]` 
Would you be open to merging it if I opened a PR?

**Comment by timc1** [comment]
@maferland are you referring to using `cmd+[any key]` to toggle `kbar`? If so you already can [here](https://github.com/timc1/kbar/blob/main/src/types.ts#L69).

**Comment by maferland** [comment]
No, sorry, I meant using `cmd+[any key]` as the shortcut for an action.

**Comment by timc1** [comment]
You can do that now, no? `$mod+key` where `$mod` would be cmd

**Comment by maferland** [comment]
Hmm, maybe I'm just getting the syntax wrong?

I tried a variety of syntaxes 👇 

```tsx
  useRegisterActions(
    [
      createAction({
        name: 'Test',
        shortcut: ['cmd+b'],
        perform: () => alert('cmd+b'),
      }),
      createAction({
        name: 'Test',
        shortcut: ['$cmd+b'],
        perform: () => alert('cmd+b'),
      }),
      createAction({
        name: 'Test',
        shortcut: ['command+b'],
        perform: () => alert('command+b'),
      }),
      createAction({
        name: 'Test',
        shortcut: ['meta+b'],
        perform: () => alert('meta+b'),
      }),
      createAction({
        name: 'Test',
        shortcut: ['meta', 'b'],
        perform: () => alert('meta, b'),
      }),
      createAction({
        name: 'Test',
        shortcut: ['cmd', 'b'],
        perform: () => alert('cmd, b'),
      }),
    ],
    [],
  );
```

None of that works.
Using `['b']` alone for instance will work. Same for  `['n', 'b']`

**Comment by timc1** [comment]
Rather than `$cmd` can you use `$mod`?

**Comment by maferland** [comment]
@timc1 Ok, I got it now. Found my answer in [tinykeys documentation](https://jamiebuilds.github.io/tinykeys/)

`$mod+key` does work. `$mod` does not need to be replaced by `cmd` or `command` 🫠
