### ISSUE TITLE
Add Synonyms

### ISSUE THREAD

**Issue by deadcoder0904** [timc1/kbar#170]
A prop called `aliases` would be cool. Here's a blog from Superhuman talking about it → https://blog.superhuman.com/how-to-build-a-remarkable-command-palette/

<img width="670" alt="Screenshot 2022-02-05 at 5 49 45 PM" src="https://user-images.githubusercontent.com/16436270/152641843-0d388ae7-514f-4527-bffe-1fa6f31568ab.png">

**Comment by deadcoder0904** [comment]
<img width="670" alt="Screenshot 2022-02-05 at 5 51 45 PM" src="https://user-images.githubusercontent.com/16436270/152641896-3b0194da-4926-4524-9baf-351840894789.png">

**Comment by lavgup** [comment]
Would this be any different than the `keywords` prop currently available?

**Comment by deadcoder0904** [comment]
Oh didn't knew there was a `keywords` prop but kinda looks similar although I do prefer the wording `aliases` as it makes more sense.

What about the 2nd image? I think this is helpful to show people the same thing but using their own wording.

**Comment by timc1** [comment]
Hey @deadcoder0904 this is a great idea! 

`aliases` is a UI enhancement while the current `keywords` is purely functional. I think the question here now is do we add this as part of the `Action` data structure, or should we introduce a `custom` field which would make adding more than just `aliases` available to developers

**Comment by deadcoder0904** [comment]
well, i haven't implemented `kbar` yet so not sure i have anything to add but would love to see it implemented.

another thing is it could look more polished like when you press <kbd>⌘ K</kbd> on [Tailwind UI](https://tailwindui.com/). currently, it looks a bit sharp.
