### ISSUE TITLE
Seems not all shortcuts are working

### ISSUE THREAD

**Issue by thecoorum** [timc1/kbar#179]
## Issue
I'm registering an action that has `shortcut: ['control', 'o']` but on triggering this shortcut while KBar is closed does nothing. I've taken a look and seems this shortcut is not bonded to any Chrome actions

## Expected
The shortcut is working as expected

**Comment by timc1** [comment]
Hey @thecoorum – anything showing up in the console which might help? I did a sanity check using the example repository and `["control", "o"]` works as expected.
