### ISSUE TITLE
tinykeys_1.default is not a function

### ISSUE THREAD

**Issue by SimonBellucci** [timc1/kbar#182]
After installing `kbar v0.1.0-beta.29` on a fresh React App I'm running into this issue :

```
TypeError: (0 , tinykeys_1.default) is not a function
```

Sandbox : https://codesandbox.io/s/admiring-saha-q6b1my?file=/src/App.js

Looks like the issue comes from `tinykeys v1.3.0` as spotted here [#138](https://github.com/jamiebuilds/tinykeys/issues/138)

**Comment by timc1** [comment]
Thanks @SimonBellucci for catching this – we'll roll back for now (latest will be `beta.30` which will point to `beta.28`). Looks like `tinykeys` is looking to revamp their API as well, so I will revisit the keybinding this weekend :-)

**Comment by timc1** [comment]
Hey @SimonBellucci - this should be fixed in [`v0.1.0-beta.31`](https://www.npmjs.com/package/kbar/v/0.1.0-beta.31) – give it a shot! :-)

**Comment by SimonBellucci** [comment]
Hey @timc1, it works like a charm ! Thank you 🙏 !
