### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by nandorojo** [timc1/kbar#183]
Huge fan of kbar. I'm thinking of building a kbar-type library that works with React Native/React Native Web. Do you think the best way to do that is to just fork kbar, or is there a way for the React Native library to import headless logic from kbar to power a lot of it?

My current thinking is, on iOS, the command pallet could be a bottom sheet triggered by shaking the device.

Curious to hear if you have any thoughts on that, figured I'd pose it here. Feel free to transfer this to a discussion.

**Comment by Rychillie** [comment]
@nandorojo I'm very interested in using KBar with React-Native, more specifically in projects with [Solito](https://github.com/nandorojo/solito), I have experience in the web, maybe we can try to do something for React-native/Web?
