### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by kasperaamodt** [timc1/kbar#192]
Hi, 

I have installed this package and set it up according to the docs. When I press command + k, I get this error:

`TypeError: Cannot read properties of undefined (reading 'length')`

`Call Stack
KBarResults
node_modules/kbar/lib/KBarResults.js (48:0)`

This is my _app.js file in next.js

`import { ThemeProvider } from "next-themes";
import { createElement } from "react";
import { setup } from "goober";
import { prefix } from "goober/prefixer";
import "../style/global.css";

import {
    KBarProvider,
    KBarPortal,
    KBarPositioner,
    KBarAnimator,
    KBarSearch,
    KBarResults
} from "kbar";

setup(createElement, prefix);

function MyApp({ Component, pageProps }) {
    const actions = [
        {
            id: "blog",
            name: "Blog",
            shortcut: ["b"],
            keywords: "writing words",
            perform: () => (window.location.pathname = "blog")
        },
        {
            id: "contact",
            name: "Contact",
            shortcut: ["c"],
            keywords: "email",
            perform: () => (window.location.pathname = "contact")
        }
    ];

    return (
        <ThemeProvider>
            <KBarProvider actions={actions}>
                <KBarPortal>
                    <KBarPositioner>
                        <KBarAnimator>
                            <KBarSearch />
                            <KBarResults />
                        </KBarAnimator>
                    </KBarPositioner>
                </KBarPortal>
                <Component {...pageProps} />
            </KBarProvider>
        </ThemeProvider>
    );
}

export default MyApp;
`

**Comment by chinchang** [comment]
Exactly same with me when using with Next.js

**Comment by chinchang** [comment]
Ah I get it now. `<KBarResults/>` can't be used as it is, as shown on project homepage. It needs you to render the results as its children like so:

```
import {
  // ...
  KBarResults,
  useMatches,
} from "kbar";

// ...
// <KBarAnimator>
//   <KBarSearch />
<RenderResults />
// ...

function RenderResults() {
  const { results } = useMatches();
    
    return (
      <KBarResults
      items={results}
      onRender={({ item, active }) =>
      typeof item === "string" ? (
        <div>{item}</div>
        ) : (
          <div
          style={{
            background: active ? "#eee" : "transparent",
          }}
          >
          {item.name}
          </div>
          )
        }
      />
    );
}
```
