### ISSUE TITLE
ActionsInterface changes not going to state

### ISSUE THREAD

**Issue by gelicia** [timc1/kbar#196]
I'm trying to use kbar so we init with an empty array of actions, and then load in actions later. I accomplish this with something like the following 

```
  const [actions, setActions] = useState<Action[]>([]);
  const { query } = useKBar();

  useEffect(() => {
    const addActions = async () => {
      const staticActions = getStaticActions();
      const dynamicNavActions = await getNavActionsBasedOnCall();
      setActions([...staticActions, ...dynamicNavActions]);
    };
    addActions();
  }, []);

  useRegisterActions(!query ? [] : actions, [actions, query]);
  ```

The component returns, in part...

```
 <KBarProvider actions={actions}>
 ```

I've also tried initing `KBarProvider` with the static actions response and then using `useRegisterActions` to load in the dynamic actions from that response, but I get the same problem where the `actionsInterface` gets what I need but it isn't added to the state. 

These changes have it work, but it's far more likely I'm missing something... https://github.com/timc1/kbar/pull/195

**Comment by timc1** [comment]
Hey @gelicia! The initial list of actions that we pass to the provider are memoized, so passing new actions to the provider will not do anything. If you want to dynamically add actions, you'll need to use `useRegisterActions` within a component nested inside the provider.
