### ISSUE TITLE
Section and Action elements overlap

### ISSUE THREAD

**Issue by OmkarK45** [timc1/kbar#197]
Alright I'm not really sure if it is a CSS Issue or tailwindCSS issue, but when I scroll in KBar window, the topmost section text gets overlapped
![image](https://user-images.githubusercontent.com/45557594/161115937-40094d6f-2372-44f2-bba6-8d5f7e287c4e.png)
![image](https://user-images.githubusercontent.com/45557594/161116239-a0f6656b-feee-4278-80bd-d6ca2e40be61.png)

Live : https://omkarkulkarni.vercel.app/
Reproduction Repo : https://github.com/OmkarK45/omkarkulkarni.dev/tree/main/components/KBar

Any help would be appreciated!

**Comment by AkashRajpurohit** [comment]
Hi @OmkarK45 seems like you are also facing the issue similar to what's mentioned here (#208), can you verify if this issue does not occur on local development builds?

**Comment by OmkarK45** [comment]
> Hi @OmkarK45 seems like you are also facing the issue similar to what's mentioned here (#208), can you verify if this issue does not occur on local development builds?

Yes can confirm this happens in local as well as production mode. I believe it is due to the useMemo hook that memoizes the ancestors. I do not have enough time to debug this right now. If you find a solution, please ping!

**Comment by AkashRajpurohit** [comment]
https://github.com/timc1/kbar/issues/208#issuecomment-1114199680

**Comment by OmkarK45** [comment]
@AkashRajpurohit did you find any solution? I do not have preact in my build pipeline

**Comment by AkashRajpurohit** [comment]
I think you do, check your next.config.js

**Comment by OmkarK45** [comment]
> I think you do, check your next.config.js

oh yeah you are right! So the solution is to disable preact right?

**Comment by AkashRajpurohit** [comment]
Yes, I've disabled it for now till there is a fix for it with preact.
