### ISSUE TITLE
React 18 Compatibility

### ISSUE THREAD

**Issue by JuandaGarcia** [timc1/kbar#199]
Currently Kbar does not have react 18 support so there are some problems for example with the definitions when using Typescript.

In React 18 the way of typing components that receive a children component changed, so when creating a project with the latest version of react using typescript Kbar components that receive a children give an error.

![image](https://user-images.githubusercontent.com/39936759/162594614-85f3c318-0a6d-4d16-b69d-dca9ea7a568c.png)

To fix it you can change the definitions using PropsWithChildren, example:

`const KBarProvider: React.FC<KBarProviderProps>`

to

`const KBarProvider: React.FC<PropsWithChildren<KBarProviderProps>>`

[https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71800185#71800185](https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71800185#71800185)

**Comment by AnishDe12020** [comment]
As mentioned in [this stackoverflow post[(https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71800185#71800185), a temporary fix would be to make a file called `react.d.ts` and override the types.

`react.d.ts` - 
```ts
import * as React from "@types/react";

declare module "react" {
  interface FunctionComponent<P = {}> {
    (props: PropsWithChildren<P>, context?: any): ReactElement<any, any> | null;
  }
}
```
