### ISSUE TITLE
Improve styling

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#2]
Currently, styles can be applied via props; e.g. `contentStyle`, `backgroundStyle` for `KBarContent`, and directly as `style` for `KBarSearch`. There should be a simpler way to customize styles which enable full flexibility for:

- Customizing Web Animations (Maybe not necessary? Kinda nice to have built in support for basic show/hide and height animations)
- Dialog background transitions
- Content transitions
- Search input
- Results
- *Support for styled components
- *Support for classNames

**Comment by heymartinadams** [comment]
Hey @timc1 is there a way to custom style individual words within the Search Bar?

For example, as the user types this into the search bar I want to style certain words: “**Water the garden** every _Monday_”.

Thanks!

**Comment by timc1** [comment]
@heymartinadams you can accomplish that through a custom `SearchInput` component, leveraging `useKbar` to hook into our internal state.

**Comment by heymartinadams** [comment]
Thanks, @timc1. Used this: https://github.com/timc1/kbar/blob/main/src/KBarSearch.tsx
