### ISSUE TITLE
Excluding specific section from search

### ISSUE THREAD

**Issue by careless10** [timc1/kbar#201]
Hi there,
First thanks for this amazing lib its working great,
Is there a way to exclude items from the search,

###Scenario
I am calling an api with the state->search , and extending the result, now the results are already filtered and some of them dont have the exact search value, which means they are being filtered out because they are not matching the exact word, thought they are still related to the search in our logic, so excluding this list from the search would be awesome.

Any suggestion?

**Comment by timc1** [comment]
hey @careless10, thanks!

I'm not sure I'm fully understanding this question – do you want to _only_ search within the result returned from your API?

**Comment by careless10** [comment]
I opened a PR, with a description about the case, #205 , please take a look whenever you can.
