### ISSUE TITLE
Ability to prompt user during perform

### ISSUE THREAD

**Issue by Winangel** [timc1/kbar#210]
Hello!

Great work on this library!

I'm exploring the possibilities it offers, but I am under the impression the usage could be better if it let the user enter some parameters before or while executing an action. A little bit like vscode's cmd+p prompt. This would allow a whole new class of actions to take place within kbar prompt.

**Comment by timc1** [comment]
Hey @Winangel! Do you have a specific example within VSCode's cmd+p?

**Comment by Winangel** [comment]
@timc1
example: create a new git branch (in git extension).
User need to provide a branch name, before executing the command.
