### ISSUE TITLE
[FEATURE REQ]: Ability to trigger custom functions when navigating kbar

### ISSUE THREAD

**Issue by AnishDe12020** [timc1/kbar#211]
It would be cool if we could trigger custom functions when one presses the up or down key. These functions can be passed into `KBarResult`. It would also be awesome if they have the select item's ref and item object passed in as function arguments.

Use case: implementing the following effect for transition between kbar items - https://emilkowal.ski/ui/tabs (here it is a navbar example but the implementation will be similar for items in kbar, I need access to the item ref though).

**Comment by timc1** [comment]
You can build this UI based on the current active rendered item? 

https://twitter.com/timcchang/status/1485259931758567433?s=21&t=odnl1ISDIKrGPNHUt4Ushg
