### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#216]
- Add the ability to always display certain results regardless of search
- Add the ability to only search within a specific category
  - Perhaps excluding specific categories from search? Food for though 🤔

**Comment by gaganmeet** [comment]
@timc1  I went through some code and I found collectChildren function being responsible for it
```
function collectChildren(actions, all) {
            if (all === void 0) { all = actionsClone; }
            for (var i = 0; i < 0; i++) {
                if (actions[i].children.length > 0) {
                    var childsChildren = actions[i].children;
                    for (var i_1 = 0; i_1 < childsChildren.length; i_1++) {
                        all.push(childsChildren[i_1]);
                    }
                    collectChildren(actions[i].children, all);
                }
            }
            return all;
        }
```
Will it be a good idea to provide the level of indexing we want to do?
I have removed this code for our project as we needed search indexing till 1 level only

**Comment by eMerzh** [comment]
hey @timc1  ... i'm aslo interested in this ... 
like having a low prio action to launch a full fledge search
like 

```
#  term
- action 1 term
- action 2 term
- search for : "term"
```
do you see a way to do that easily?
