### ISSUE TITLE
[feature]: Allow looping when navigating the results list

### ISSUE THREAD

**Issue by AkashRajpurohit** [timc1/kbar#224]
When a user reaches the end of the list, on pressing the `ArrowDown` the list selection does not move back to the first item.

We can add a feature to allow the list to continue the looping when it reaches the end of either side of the list, i.e. go to first item when clicked `ArrowDown` on last item and go to last item when clicked `ArrowUp` on first item.

We can take an optional prop for the KbarResults, something like `allowLoop` and maintain backward compatibility by having its default value as false which is the current behavior. When set to true, we can enable the flow mentioned above.

If this is something you feel can add value to the package, I can work on this feature and send a PR :)

**Comment by benatpigment** [comment]
+1 for this feature

**Comment by AkashRajpurohit** [comment]
@benatpigment If you would like to review, I have created an PR for adding this #226 :)
