### ISSUE TITLE
Create dynamic actions based on user's query input

### ISSUE THREAD

**Issue by jferrettiboke** [timc1/kbar#227]
I'd like to add some actions based on user's query input. Example:

1. User starts typing in “tesl”.
2. Kbar renders “tesla.com” and “twitter.com/tesla”. This can be whatever the developer wants to be actually. It just needs creativity.
3. User selects the appropriate one.

Spotlight has support for this. GitHub as well. Having the primitives that allow us to build something similar would be great.

My questions are:

- Is there any way to access what the user is typing in?
- Can we create actions after users type something in? Or, can we only create actions before users start typing something in?
- Can we edit the action name dynamically so that we can add fallbacks like "Search for **[query]** on the web"?

**Comment by Cygnusfear** [comment]
I'm digging around in the source, maybe this helps as a starting point: 

- You can access the current searchQuery and your actions with the useKBar hook: 
```
  const { search } = useKBar(state => ({
    search: state.searchQuery,
    actions: state.actions
  }))
```
- The docs describe a `useRegisterActions` hook, which can be used to dynamically add actions

**Comment by jferrettiboke** [comment]
Shut up, bot. Keep it alive.

**Comment by jferrettiboke** [comment]
Keep it open, bot.

**Comment by jferrettiboke** [comment]
Keep it open, bot. 🙃

**Comment by jferrettiboke** [comment]
Hey 🤖! Don’t mark it as stale. Thanks!

**Comment by jferrettiboke** [comment]
Do not close it!
