### ISSUE TITLE
Use action shortcuts with Ctrl/cmd + shift + <any key>

### ISSUE THREAD

**Issue by alishaz-polymath** [timc1/kbar#229]
Hey, First of all, awesome library 🙏 
I was wondering if there's a way to hook up the action shortcuts with shift and cmd/ctrl keys as part of the combination because currently I am often moving to a different page (because of action shortcut) even when my intention is to type something on the page. The only way to avoid this so far has been to add at least 2-3 keys for a shortcut but it would make more sense if we could add `Cmd + Shift + <any key>` instead

Thanks 🙌

**Comment by dehmer** [comment]
As far as I can see, that's easily achieved. Have a look at https://github.com/jamiebuilds/tinykeys
`shortcut: ['$mod+Shift+D']` for example works nicely.

But be careful: I just started playing with kbar yesterday. I have no idea if it's supposed to be done this way.

**Comment by thecoorum** [comment]
Hey, I created PR for the behavior you described. Also needed such functionality, so maybe we could upvote the issue

https://github.com/timc1/kbar/pull/242
