### ISSUE TITLE
Memory leak in useRegisterActions hook

### ISSUE THREAD

**Issue by brydar** [timc1/kbar#233]
Hi, I stumbled upon an apparent memory leak in the `useRegisterActions` hook.

### Step to reproduce:
Open this codeSandbox: https://codesandbox.io/s/compassionate-mirzakhani-mg3wgc?file=/src/App.js
From the view here: https://mg3wgc.csb.app/

By inspecting the browser memory we can find that the `Leaker` class is kept in memory, more generally the action provider component state is leaked.

With **1** action registered (ProvideStuff)
<img width="1008" alt="CleanShot 2022-07-22 at 18 34 47@2x" src="https://user-images.githubusercontent.com/1957079/180484522-e4b1a08b-ea0a-4ae5-82ab-1e2926a93bf2.png">

Without any action registered (Nothing)
<img width="1009" alt="CleanShot 2022-07-22 at 18 39 47@2x" src="https://user-images.githubusercontent.com/1957079/180485118-7ae57e4c-2d33-46a5-9d1f-564b5a98d6f6.png">
istered

--- 

`useRegisterActions` hook is apparently capturing the whole application state that can be linked to the `perform` lambda. In my case we had to indirect the `perform` function to a `WeakRef` to let the browser garbage collector clean it when the action is not registered anymore.

We didn't identify the underlying issue in the `useRegisterActions` file, maybe a stale closure or something, do you have an idea?

Thanks for the great work 👏

**Comment by timc1** [comment]
Hey @brydar apologies for the late response – looking into this asap. Thank you!

**Comment by timc1** [comment]
Alright, so I've been playing around with this sandbox for a bit – thank you for the environment!

Between each snapshot, it looks like you have your filter set to `All object`, which I'd imagine it's more accurate to filter the allocated objects between runs:

<img width="366" alt="Screen Shot 2022-08-08 at 5 40 33 PM" src="https://user-images.githubusercontent.com/12195101/183519793-9900d82b-7aaa-4b3c-8f1b-2f5544ee1c2b.png">

When doing so, it shouldn't display the previous run's `Leaker`:

https://user-images.githubusercontent.com/12195101/183519978-f116fc10-71cd-425e-842f-ce5c0fc043f9.mov

I'm not sure how ya'll are using this class instance in your site, but if you were using `mobx` `autorun`, for instance, within that `Leaker` class, you'd need to do your own cleanup when `ProvideStuff` unmounts.

**Comment by dubzzz** [comment]
Totally forgot to add some more context to it. But it seems that there _was_ (or _is_) a leak.

**Comment by dubzzz** [comment]
@timc1 In your footage we can see the following filter: "allocated between Snapshot 7 and Snapshot 8".

![image](https://user-images.githubusercontent.com/5300235/195070628-176f0a3e-d515-44b9-a428-82e7d6b67664.png)

So it seems normal not to see Leaker at this point as it has been allocated before Snapshot 7. In other words not seeing it is expected at this point because it has not been part of this incremental change; but it should have been released so if you check what you have in Snapshot 8 you should not find it.

I implemented a workaround version to avoid the leak of the library. I'll send you a link towards a patch version of it so that you can see the difference.

**Comment by dubzzz** [comment]
Here is a leak-free version: https://codesandbox.io/s/strange-chihiro-83vexl?file=/src/App.js or https://83vexl.csb.app/

**Comment by dubzzz** [comment]
With the leaky version: https://mg3wgc.csb.app/
![kbar-leak](https://user-images.githubusercontent.com/5300235/195072845-b4c7172b-3149-48d9-869a-461a1d4d7e27.gif)

Without the leak: https://83vexl.csb.app/
![kbar-no-leak](https://user-images.githubusercontent.com/5300235/195072497-2caf143c-0bff-4d1d-9d3d-06a2067bab02.gif)
