### ISSUE TITLE
Allow disableCloseOnOuterClick at times by passing an optional props on KBarAnimator

### ISSUE THREAD

**Issue by drenther** [timc1/kbar#248]
## Why I needed this?

![CleanShot 2022-09-22 at 12 20 53](https://user-images.githubusercontent.com/12991390/191678140-9f347843-2055-4548-ac13-1d56f81d56a7.png)

- I needed to create popover select menu for changing filter values in the search bar. The popover was opening in it's own portal and click interactions on the menu was closing the KBar view due to the `useOuterClick` logic in KBarAnimator.
- I tried passing this as option but since options are cached the first time in a ref, a boolean flag changing based on the popover open or close state couldn't not be handled. Hence passing the boolean flag directly as a prop to `KBarAnimator`

> If an acceptable usecase - I can create a PR for this.

## Current Approach I took to solve this

> This is what I am doing with `patch-package` right now for my usecase

For now, I used [patch-package](https://github.com/ds300/patch-package) to patch `kbar@0.1.0-beta.36` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/kbar/lib/KBarAnimator.d.ts b/node_modules/kbar/lib/KBarAnimator.d.ts
index 934c3b1..184a22f 100644
--- a/node_modules/kbar/lib/KBarAnimator.d.ts
+++ b/node_modules/kbar/lib/KBarAnimator.d.ts
@@ -2,6 +2,7 @@ import * as React from "react";
 interface KBarAnimatorProps {
     style?: React.CSSProperties;
     className?: string;
+    disableCloseOnOuterClick?: boolean;
 }
 export declare const KBarAnimator: React.FC<React.PropsWithChildren<KBarAnimatorProps>>;
 export {};
diff --git a/node_modules/kbar/lib/KBarAnimator.js b/node_modules/kbar/lib/KBarAnimator.js
index 73cbf18..6f9b433 100644
--- a/node_modules/kbar/lib/KBarAnimator.js
+++ b/node_modules/kbar/lib/KBarAnimator.js
@@ -56,7 +56,7 @@ var bumpAnimationKeyframes = [
 ];
 var KBarAnimator = function (_a) {
     var _b, _c;
-    var children = _a.children, style = _a.style, className = _a.className;
+    var children = _a.children, style = _a.style, className = _a.className, disableCloseOnOuterClick = _a.disableCloseOnOuterClick;
     var _d = (0, useKBar_1.useKBar)(function (state) { return ({
         visualState: state.visualState,
         currentRootActionId: state.currentRootActionId,
@@ -136,6 +136,7 @@ var KBarAnimator = function (_a) {
         }
     }, [currentRootActionId, enterMs]);
     (0, utils_1.useOuterClick)(outerRef, function () {
+        if (disableCloseOnOuterClick) return;
         var _a, _b;
         query.setVisualState(types_1.VisualState.animatingOut);
         (_b = (_a = options.callbacks) === null || _a === void 0 ? void 0 : _a.onClose) === null || _b === void 0 ? void 0 : _b.call(_a);
```

**Comment by timc1** [comment]
@drenther Apologies for the late response; if you like, feel free to give this a shot!

**Comment by drenther** [comment]
No problem @timc1 :)

I have been using patch-package for now for this functionality. Will check if I can whip up a PR for this next week.
