### ISSUE TITLE
Kbar very slow under certain condition

### ISSUE THREAD

**Issue by raRaRa** [timc1/kbar#252]
When you have many actions (maybe 50-100ish), and some of them contain keywords such as "bla is a member in {teamName}", then kbar becomes almost unresponsive when typing "bla is a". This happens immediately after typing "a".

I have a feeling this is related to command score that is used under the hood. Would it be possible to somehow disable command score in kbar?

Thanks.

**Comment by raRaRa** [comment]
Here's a snippet that reproduces this issue:

```
for (let i = 0; i < 100; i++) {
      updatedPeopleActions.push(
        createAction({
          name: `John${i} is a member in Team Test`,
          icon: 'layers-three-01',
          keywords: [
            `John${i} is a member in ${i}`,
            `Teams where John${i} is a member`,
          ]
            .filter((word) => !!word)
            .join(', '),
          perform: () => console.log('Hello'),
        })
      );
    }
```

In my actual code `John${i}` is an actual person name and it's not repeating like that. But this code is enough to show how unresponsive kbar becomes with these actions.

Just type something like 'John is a ..." and it becomes very sluggish after typing "a".

**Comment by timc1** [comment]
Hey @raRaRa 👋 

How are you building `updatedPeopleActions`? ie; is the `updatedPeopleActions` list getting rebuilt every time you type something into the search bar?

**Comment by raRaRa** [comment]
Can you try it with a similar query as I am using, where you use something like "Where bla is ...". Everything is fast for me as well until I use words such as "is".

**Comment by timc1** [comment]
Ah, I am able to reproduce it; it is due to `command-score`. Will investigate.

**Comment by raRaRa** [comment]
Ah cool thanks, is it possible to bypass command-score completely, or replace it with my own function?

**Comment by timc1** [comment]
You can always just fork a copy of `useMatches` and add your own custom matching logic! Pass the results to `KBarResults` and you should be good to go.

**Comment by timc1** [comment]
Following up here: https://github.com/timc1/kbar/issues/255
