### ISSUE TITLE
Replace @reach/portal

### ISSUE THREAD

**Issue by olayway** [timc1/kbar#256]
Hello!
It seems that one of your dependencies - `@reach/portal` still requires React 16 or 17, whereas you have already listed React 18 in your peers.

```bash
 WARN  Issues with peer dependencies found
packages/template
└─┬ kbar 0.1.0-beta.38
  ├─┬ @reach/portal 0.16.2
  │ ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
  │ ├── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
  │ └─┬ @reach/utils 0.16.0
  │   ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
  │   └── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
  └─┬ react-virtual 2.10.4
    └── ✕ unmet peer react@"^16.6.3 || ^17.0.0": found 18.2.0

```

Let me know if I should create an issue in their repo as well. Thank you for all your great work!

**Comment by timc1** [comment]
Hey @olayway! This will work fine with React 18 even though it isn't explicitly listed. However, it's best if we move to using a separate portal lib as Reach isn't actively maintained.

**Comment by olayway** [comment]
@timc1 Cool, thank you for your reply! 🌼
