### ISSUE TITLE
Cant register child action dynamically.

### ISSUE THREAD

**Issue by jameswong3388** [timc1/kbar#261]
I had root action for article search purposes. All the articles were retrieved from an API `https://jameswong.vercel.app/api/articles/all`, then it is being mapped to create child actions using the method `createActions()`. 

But when the page reloaded, nothing appeared but the root actions. Where did I do it wrong?

![image](https://user-images.githubusercontent.com/87692325/202935862-1102335d-f113-4b35-bc8e-6b981e847c6a.png)

```
import { createAction, useRegisterActions } from 'kbar'
import * as React from 'react'
import { useRouter } from 'next/router'
import fetcher from '../../lib/fetcher'
import { type Action } from 'kbar'
import { Articles } from '../../lib/types'

function NewspaperIcon(props: React.ComponentProps<'svg'>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      strokeWidth="1.5"
      stroke="currentColor"
      {...props}
    >
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        d="M12 7.5h1.5m-1.5 3h1.5m-7.5 3h7.5m-7.5 3h7.5m3-9h3.375c.621 0 1.125.504 1.125 1.125V18a2.25 2.25 0 01-2.25 2.25M16.5 7.5V18a2.25 2.25 0 002.25 2.25M16.5 7.5V4.875c0-.621-.504-1.125-1.125-1.125H4.125C3.504 3.75 3 4.254 3 4.875V18a2.25 2.25 0 002.25 2.25h13.5M6 7.5h3v3H6v-3z"
      />
    </svg>
  )
}

export default function useArticleActions() {
  const router = useRouter()
  const [articles, setArticles] = React.useState([])

  React.useEffect(() => {
    fetcher('/api/articles/all')
      .then((data) => {
        setArticles(data)
      })
      .catch((error) => {
        console.log(error)
      })
  }, [])

  const rootActions = {
    id: 'Articles',
    name: 'Search Articles...',
    keywords: 'search for articles',
    section: 'Articles',
    icon: <NewspaperIcon className="h-5 w-5" />,
    shortcut: ['Shift+A'],
  }

  const childActions = articles.map((article: Articles) =>
    createAction({
      name: article.title,
      keywords: article.description,
      parent: 'Articles',
      section: 'Articles',
      icon: <NewspaperIcon className="h-5 w-5" />,
      perform: () => {
        router.push(`/articles/${article.slug}`)
      },
    })
  )

  useRegisterActions([rootActions, ...childActions].filter(Boolean) as Action[])
}
```

**Desired result**
![image](https://user-images.githubusercontent.com/87692325/202936108-86a6d050-f832-4a90-ac01-4075259b8569.png)

**Comment by timc1** [comment]
@jameswong3388 that's because `useRegisterActions` is registering the initial `articles` array only. You'll need to pass your `articles` state value as a dependency to the hook, so `useRegisterActions` can update when your async data fetch resolves:

```
  const childActions = useMemo(() => articles.map((article: Articles) =>
    createAction({
      name: article.title,
      keywords: article.description,
      parent: 'Articles',
      section: 'Articles',
      icon: <NewspaperIcon className="h-5 w-5" />,
      perform: () => {
        router.push(`/articles/${article.slug}`)
      },
    })
  ), [articles])

useRegisterActions([rootActions, ...childActions].filter(Boolean), [childActions])
```

**Comment by jameswong3388** [comment]
@timc1, ahhh i see, Thank You so much ! really got a lot of stuff to learn from you 😊!

**Comment by jameswong3388** [comment]
@timc1, after i made those changes, although the problem is solved, but the actions began flickering when I hovered over them. 

**Before**

[screen-capture.webm](https://user-images.githubusercontent.com/87692325/203555703-246d6d50-10c7-4810-a124-93abcb6e5fd6.webm)

**After**

[screen-capture (1).webm](https://user-images.githubusercontent.com/87692325/203555379-cfbfe2b9-7e59-4511-b505-cbaeb516a112.webm)

**Comment by timc1** [comment]
Yeah that `/all` endpoint should only get hit once. `kbar` is flickering due to `useRegisterActions` rerendering every time that request comes in.

**Comment by jameswong3388** [comment]
Thx @timc1, i have solved the problem.

**Comment by jameswong3388** [comment]
@timc1 I also noticed that the position of the actions dropped to the bottom after promises is resolved.

![image](https://user-images.githubusercontent.com/87692325/203650923-d3219aeb-7993-42df-89e2-dad6b94964e4.png)

**Comment by timc1** [comment]
@jameswong3388 that is expected as we order by priority; actions with the same priority are ordered based on the order they were registered if no priority is set.

**Comment by jameswong3388** [comment]
@timc1 right, that make sense.
