### ISSUE TITLE
react 18 unmet peer dependencies

### ISSUE THREAD

**Issue by tjx666** [timc1/kbar#262]
![image](https://user-images.githubusercontent.com/41773861/203251374-d64d5c61-3641-4024-94d5-65461aeac4df.png)

**Comment by oskarrough** [comment]
Maybe it was already fixed in https://github.com/timc1/kbar/pull/257. Needs a release?

**Comment by timc1** [comment]
This should be fixed in the [latest release](https://www.npmjs.com/package/kbar/v/0.1.0-beta.39)
