### ISSUE TITLE
Safari exits full screen when closing the menu using the escape key

### ISSUE THREAD

**Issue by piofinn** [timc1/kbar#264]
## Bug 🐞

The escape key is bound to exiting full screen mode in Safari by default. Therefore the browser window exits full screen when using escape to close the kbar dialog.

## Suggested fix ✨

Set `event.preventDefault()` where the escape key press is handled.

**Comment by jakewtaylor** [comment]
I'm still seeing this happen in chromium browsers, but _only_ if I first navigate into a group, then `backspace` back to the top, then `Escape` - closes the kbar dialog but also exits fullscreen.

Any ideas @timc1 ?
