### ISSUE TITLE
Duplicate actions with useRegisterActions

### ISSUE THREAD

**Issue by davidkaneda** [timc1/kbar#267]
I'm getting every result below repeated 3x in the UI, using the following code. (`useMe` is a call to `useSWR`, updates dynamically/async)

```ts
  const { me } = useMe();
  const router = useRouter(); // (Next.js router)
  const templateActions = useMemo(() => {
    const actions = [] as Action[];

    actions.push({
      id: "blank-draft",
      name: "Blank draft",
      section: "New",
      parent: "new-template",
      keywords: "new doc draft",
      perform: () => router.push("/edit/"),
      priority: 1,
    });

    if (me?.stripeCustomer?.isActive) {
      actions.push(
        ...Object.entries(templates).map(([key, template]) => ({
          id: key,
          section: "New",
          name: `${template.title}`,
          parent: "new-template",
          perform: () => router.push(`/edit/?template=${key}`),
        }))
      );
    }

    return actions;
  }, [me, router]);

  useRegisterActions(templateActions, [templateActions]);
```

It feels like the call to `unregister` in `useRegisterActions` isn't actually removing them each time the deps change.

**Comment by davidkaneda** [comment]
Ah, I just looked at the source and see that `unregister` is just being called on unmount, so not when the deps actually change. Is that intentional?

**Comment by timc1** [comment]
`unregister` is called whenever your dependencies change; it works just as a `useEffect` would.

- Where is `templates` coming from?
- What's the output of `templateActions`? are there actions with duplicate `id`s there?

**Comment by davidkaneda** [comment]
`templates` comes from a static `import`, there shouldn't be any duplicates in the `templateActions` output-

**Comment by davidkaneda** [comment]
Interestingly, the duplication doesn't happen if I remove the "parent" field. "new-template" is a parent action I define statically somewhere else-

**Comment by davidkaneda** [comment]
Moving the parent action into the `useMemo` seems to have fixed it-
