### ISSUE TITLE
Can't open Kbar programmatically, cannot read properties of undefined (reading 'toggle')

### ISSUE THREAD

**Issue by saadee** [timc1/kbar#273]
Hi, I need to open the Kbar programmatically. on an onClick function 

I saw previous Closed issues it was mentioned to use `useKbar` hook , but it doesn't work like that 

here's my code.  I am using the kbar version `^0.1.0-beta.39`

>     const { query } = useKBar();

using it like this 

>             <button onClick={() => query.toggle()}>Toggle</button>

Can somebody guide me if I am doing anything wrong? 

here's screenshot of error in console 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/36909557/209679011-104442f8-7f78-4751-8623-bd068724884d.png">

**Comment by timc1** [comment]
Are you using `useKbar` within a component nested in a `KBarProvider`?

**Comment by bcutler** [comment]
I've got the same issue and it is nested in a KBarProvider

**Comment by timc1** [comment]
@bcutler Can you reproduce this within a codesandbox?

**Comment by bcutler** [comment]
I'm sure I'm doing something dumb here: https://github.com/bcutler/kbar-toggle-bug. Thanks for taking a look!

**Comment by bcutler** [comment]
I got the issue worked out by wrapping the KBarProvider around my entire app. Thanks @timc1 — I ♥️ kbar
