### ISSUE TITLE
Invariant failed from tiny-variantt package

### ISSUE THREAD

**Issue by iamgabrielsoft** [timc1/kbar#276]
anytime i hit ctrl + k i get this error from the package, i guess its from the tiny-variant package installed on kbar
![Screenshot from 2023-01-15 08-44-38](https://user-images.githubusercontent.com/71671874/212539318-86e6031a-48ee-467c-b9c5-d304ea08d70e.png)

**Comment by timc1** [comment]
Did you apply `inputRefSetter` to your search input?

**Comment by iamgabrielsoft** [comment]
i haven't applied inputRefSetter
