### ISSUE TITLE
commandScore expensive calculation when action's .name or .keywords or .subtitle are longer

### ISSUE THREAD

**Issue by panchicore** [timc1/kbar#279]
https://github.com/timc1/kbar/blob/b4666e06d2df1be9a84e03132e6d9f4c56f17f3c/src/useMatches.tsx#L192-L195

`commandScore` execution is slow when having matches with detailed descriptions on `action.subtitle`, when the description length is > 100 characters using the typing the command results in input lag. The use case is a text search in which resulting actions contain highlighted matches of the keyword match.

I am adding the actions with `useRegisterActions` after matches are found, maybe I should be using a different approach?

**Comment by timc1** [comment]
Yep this is known! (https://github.com/timc1/kbar/issues/255) For now if absolutely needed, you can stub out command score or reduce the length of the compared word

**Comment by steveoni** [comment]
@panchicore you can check if this fix your issue #325
