### ISSUE TITLE
Feature Request: Actions as links

### ISSUE THREAD

**Issue by joshhunt** [timc1/kbar#281]
When using kbar to render navigation links, you can't right click -> open in new tab because all actions are rendered as divs.

We would like to be able to set a url property on Actions, and kbar would render them as `<a />` links instead of divs to get proper link browser behaviour.

Possibly consumers might like to pass in their own link component to use with something like react-router.

**Comment by joshhunt** [comment]
We've copied KBarResults into our codebase to render actions with urls as links. Relevent changes are [rendering as `<a />` if there's a url](https://github.com/grafana/grafana/pull/62315/files#diff-6be82d5963f5446e5b709fc828d6e191fd838b11faa0a4470b5fc5ec418fd36eR198-R222), and [not closing kbar when executing an action while ctrl/cmd/shift keys are clicked](https://github.com/grafana/grafana/pull/62315/files#diff-6be82d5963f5446e5b709fc828d6e191fd838b11faa0a4470b5fc5ec418fd36eR124-R127).

Is this something you would welcome a PR for? Any changes from our implementation?

**Comment by timc1** [comment]
Hey @joshhunt, that make sense and is a pretty trivial update! Feel free to open a PR :)

**Comment by IlirEdis** [comment]
Is this a feature now? How to add a url to some of my items?
