### ISSUE TITLE
Contents gets overlapped when in more than 8.

### ISSUE THREAD

**Issue by pwnwriter** [timc1/kbar#282]
Hi, I've been facing this issue in kbar. When i deploy my site `(using netlify)` the contents of my kbar gets overlapped but in local it looks good.
 
I'm using `0.1.0-beta.36` version.

Screenshots :--> 

When deployed:

![preview](https://0x0.st/oF2G.png)

In local :

![preview](https://0x0.st/oF2D.png)

**Comment by pwnwriter** [comment]
Just checked with the latest version also, It shows the same :(

**Comment by timc1** [comment]
Mind dropping a codesandbox with the repro or link to the code you're using where you're seeing this?
