### ISSUE TITLE
Possibility to define actions that are always shown / never filtered out from the results list

### ISSUE THREAD

**Issue by aghster** [timc1/kbar#286]
I would like to be able to define actions that are always part of the results list, irrespecitve of the current search string. However, this is not possible, because actions for which `command-score` returns `0` will not be included in the results list due to:

https://github.com/timc1/kbar/blob/54b9fd8397f4bc1ad90833d1586f6f0bd0785e07/src/useMatches.tsx#L196-L198

My suggestion is that any action whose keywords include a special wildcard keyword will always be included in the results list. For example this special wildcard keyword could be `*`. 

As it seems, this could easily be implemented by ameding the above condition as follows:

```tsx
      if (score > 0 || action.keywords?.split(" ").indexOf("*") !== -1) {
        matches.push({ score, action });
      }
```

@timc1, would you consider this generally useful and add this feature to kbar?

**Comment by timc1** [comment]
@aghster I'm open to it – curious what are some of those actions you had in mind that would always be part of the list?

**Comment by aghster** [comment]
In my use case I have only two or three static actions, but depending on the search string more actions are dynamically added. However, I want the static actions to be always quickly accessible, even if a search string was entered that does not match these actions.

**Comment by eMerzh** [comment]
I have a usecase where i have a few "action" like
-toggle this
- go to Y

but i also want to fallback to an action where i go "Search ${query}" where you launch a full faceted search with criterias

**Comment by Itsnotaka** [comment]
I agree with this idea; it would be nice to have some actions to fallback on instead of showing nothing or an empty component that can't perform any actions.

**Comment by eMerzh** [comment]
I'm interested in this... Please do not close 😁
