### ISSUE TITLE
Bug: Always Adding Scrollbar Margin

### ISSUE THREAD

**Issue by EmirBoyaci** [timc1/kbar#289]
Hello,

I just tried KBar and found that it is always adding scrollbar margin even if scrollbar is not visible. I think we should add scrollbar's margin if scrollbar is actually visible. It is because, if scrollbar is not visible and we add margin, content shifting to left.

**Comment by timc1** [comment]
Can you add a screen cap or codesandbox to reproduce this issue?

**Comment by EmirBoyaci** [comment]
> Can you add a screen cap or codesandbox to reproduce this issue?

Sure, I tried in https://kbar.vercel.app/ website by removing HTML elements from Developer Tools. Here you can see the screen recording:


https://user-images.githubusercontent.com/59085992/220185059-3d64fc20-33db-454b-a48f-37cb4009267e.mp4

**Comment by timc1** [comment]
Can you use `disableScrollbarManagement `? https://github.com/timc1/kbar/blob/main/src/types.ts#L55

**Comment by EmirBoyaci** [comment]
> Can you use `disableScrollbarManagement `? https://github.com/timc1/kbar/blob/main/src/types.ts#L55

If I do and we have overflowed content (iow scrollbar is visible), then layout shifts.

**Comment by EmirBoyaci** [comment]
@timc1 yes, I remember correct. If I pass `disableScrollbarManagement: true` to KBarProvider as a option prop, then page content shifts where content overflows (iow scrollbar visible). It is like vice-versa, if I set true to `disableScrollbarManagement ` and scrollbar is visible, then layout shifts. Otherwise, without scrollbar page's layout's are shifting.

**Comment by EmirBoyaci** [comment]
Hi @timc1 do you also need reproducer for the `disableScrollbarManagement: true ` behaviour? I am currently thinking why someone did not ever faced with that issue..

**Comment by idling-mind** [comment]
I'm also facing the same issue!
