### ISSUE TITLE
item and Items in KBarResult should have same type

### ISSUE THREAD

**Issue by yogen9** [timc1/kbar#297]
either both should be `any` or `RenderParam['item']`. Is that correct assumption or is there any reason for this ? @timc1 

<img width="1054" alt="Screenshot 2023-03-14 at 10 21 59 PM" src="https://user-images.githubusercontent.com/22031931/225079616-cfab2ab9-ec96-4a5b-ab14-693a4f9e2fe0.png">

**Comment by timc1** [comment]
Yeah, `RenderParams["item"][]` would probably be preferred here.
