### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by KrallXZ** [timc1/kbar#30]
Hey,
I really like this component, but macOS have less than 10% of market share.
It would be nice to add alternative shortcuts for Windows (and probably Linux).

CTRL + K works well, menu could be opened and closed, but the shortcuts like "h for home" are not working, just nothing happens.

**Comment by timc1** [comment]
This will be fixed in the next release, likely later today/early tomorrow, with #18 :-)

**Comment by timc1** [comment]
> CTRL + K works well, menu could be opened and closed, but the shortcuts like "h for home" are not working, just nothing happens.

Will need to do some testing with Windows/Linux – will follow up here.

**Comment by timc1** [comment]
Testing this behavior through a Windows device, switching between <kbd>h</kbd> and <kbd>d</kbd> looks to work fine:

https://user-images.githubusercontent.com/12195101/133622109-f81e4c88-ddc8-4693-920c-03892495289a.mp4

**Comment by KrallXZ** [comment]
@timc1 Hey, I have MS Edge 93. 

https://user-images.githubusercontent.com/6277709/134019499-f027500f-4a7a-4916-9ac4-8cdc79dc17e5.mp4

**Comment by KrallXZ** [comment]
Oh, now I see. I thought the shortcuts are working with opened menu, but they are working only if menu is closed.

**Comment by timc1** [comment]
Oh yes, that is one point of confusion I'm sure others may face. Will keep in mind when determining how to move forward with these shortcuts 👍

**Comment by assimovt** [comment]
This is an interesting one 😉  @timc1 I've now discovered that on Ubuntu (20.04 + Chrome) it overrides default behavior. For instance, I've got `C` configured as a shortcut. On Mac, pressing only `C` executes configure KBar operation, whereas on Linux it hijacks Ctrl+C which is obviously used for copying. Is it an expected behavior, or how can I make it so that on Linux it behaves like on Mac, just pressing shortcut would do its thing.

**Comment by timc1** [comment]
Hey @assimovt! So if I'm understanding correctly, pressing `c` on a Mac works as expected, but on Linux it's rather running `ctrl`+`c`? I've never come across this, but as a first step would mapping `c` to another key; i.e. `d` be a quick fix?

**Comment by assimovt** [comment]
Yeah, that'd have been my "solution" as well, but then I was worried it hijacks all other keys, like `Ctrl+o`, etc. This is what I found and I think it's how the clipboard is handled in Unbuntu, but I am not sure:

Basically, if I `Ctrl+C` on a "textA", then do it again for the same text, my guess is that `Ctrl` is no longer triggered by the OS and it treats it as just `C`. I hope I've expressed myself clearly. In that case, yeah, it'd be just easier to remap it. 

Maybe #55 would have helped in such cases.

**Comment by timc1** [comment]
> Basically, if I Ctrl+C on a "textA", then do it again for the same text, my guess is that Ctrl is no longer triggered by the OS and it treats it as just C

That's default behavior across OSes yeah? I suppose if you're doing <kbd>ctrl</kbd>+<kbd>c</kbd> and subsequently hitting <kbd>c</kbd> without lifting <kbd>ctrl</kbd> that's what would happen.

**Comment by assimovt** [comment]
Yeah, but not on Mac OS. Anyways, thanks for your help @timc1 and this awesome tool 🙌🏽

**Comment by austincondiff** [comment]
Sorry to open a closed issue but in Windows on Chrome, Ctrl + K focuses the address bar. I am unable to open kbar search.

**Comment by timc1** [comment]
@austincondiff Try Ctrl + windows + k as a workaround
