### ISSUE TITLE
Maintaining Status

### ISSUE THREAD

**Issue by eMerzh** [timc1/kbar#308]
Hello @timc1
Thanks a lot for your work on this project... it's really neat ❤️ 

I was just noticing that there wasn't much activity around this repo lately ... 
I 100% understand that you might not have the time / energy to maintain it, or maybe you were just busy with other things and plan to come back to it later?

Anyway, i was wondering if you could update us a bit about the status ... there are some interesting PRs or forks that could improve the overall project without necessarily going feature creep

Whatever you decision, thanks :)

**Comment by timc1** [comment]
Thanks for the bump @eMerzh! :) https://github.com/timc1/kbar/issues/309
