### ISSUE TITLE
Project update!

### ISSUE THREAD

**Issue by timc1** [timc1/kbar#309]
Hey all, hope everyone is well!

You may have noticed that the project has been a bit quiet for the last few months. To be honest, I have been going through some personal matters (figuring out where life is going, interests, etc., as we all do) and have placed many projects I've had in mind, including kbar, on hold.

I don't have anything planned _for now_, but just wanted to drop a quick update that I'm still alive – just need some time for myself and exploring.

Regarding open PRs and issues, while not immediate, I will still be perusing and making sure these are kept up to date. Thanks everyone. ❤️

**Comment by eMerzh** [comment]
Thanks for the [quick] update and thanks for maintaining this :)

again, no obligation or rush to maintain this ... we appreciate the work you've already done

**Comment by dhruvilxcode** [comment]
Thanks @timc1 for building this project. Breaks are essential. I hope you take care of your health.
