### ISSUE TITLE
react 18 unmet peer dependencies

### ISSUE THREAD

**Issue by neelbrahmakshatriya** [timc1/kbar#326]
Hi 👋

Thanks for the great library. It helped me a lot.

However, I am concerned about the following warning in the latest version v0.1.0-beta.41:
![Screenshot 2023-08-08 at 1 08 18 PM](https://github.com/timc1/kbar/assets/64475785/a977287a-b514-4ff4-b39f-4a295c94e961)

In #262, @timc1 mentioned that all the warnings will be resolved in the v0.1.0-beta.39 but the above warning still persists.

I hope this warning will be resolved in the upcoming release.

**Comment by HamedMP** [comment]
Oh I just opened #330 🙈  have same issue, even `--force` doesn't work.

**Comment by Heet-Bhalodiya** [comment]
Hi

I am having the same issue. Any updates on this?

**Comment by jdross** [comment]
same here. We can get around by adding 18 support, but would be better in repo
