### ISSUE TITLE
No style

### ISSUE THREAD

**Issue by DiesIrae** [timc1/kbar#334]
Awesome project!

On:
- React 18
- Webpack

I tried the homepage example but didn't get any style:

<img width="280" alt="image" src="https://github.com/timc1/kbar/assets/473761/10b81a75-9d9c-4821-8bf6-723514052408">

How can I get the default style?

**Comment by CMOISDEAD** [comment]
By default kbar comes without styles 😞 , but you can check in `example/src/app.tsx` path in the repository to see how supposed kbar has to be styled
