### ISSUE TITLE
Search doesn't match last word when entry is coming from `useRegisterActions`

### ISSUE THREAD

**Issue by brydar** [timc1/kbar#337]
Hello! 👋 

Since version 0.1.0-beta.**42** the search matching has changed regarding the last word of the `name` of the action.

This seems to happen only on actions added using `useRegisterActions`.

### Repro
Here is a repro of the issue:
https://codesandbox.io/s/kbar-test-forked-8rj7cg?file=/src/index.js:393-418
If you search for "aaa" the results will contain the root action but not the one from the `useRegisterActions`

I tried to investigate the `useMatches` file but didn't find the fuse option that could differ from both cases 😅 

### Results
**V0.1.0-beta.41**
<img width="491" alt="brydar 2023-10-23 at 10 09 24@2x" src="https://github.com/timc1/kbar/assets/1957079/6e7ef6e0-2369-4e9b-b452-a2c766177b34">

**V0.1.0-beta.42**
<img width="518" alt="brydar 2023-10-23 at 10 10 56@2x" src="https://github.com/timc1/kbar/assets/1957079/7db37ef4-780d-44ac-bd25-34c9b7972499">

**Comment by charlesvinette** [comment]
Can confirm the issue also exists on beta3!

**Comment by dubzzz** [comment]
Based on [this page](https://www.fusejs.io/concepts/scoring-theory.html), the behaviour is expected given the current options passed to fuse. Actually we pass distance=100 and threshold=0.2, meaning that for strings longer than 0.2*100=20 characters we will have to match lots of characters before seeing them into the list of suggestions.

@timc1 Do you think there could be a way to let users configure part of fuse? I mean overriding some of the configuration to put threshold to something larger (or smaller).

**Comment by dubzzz** [comment]
I think setting the ignoreLocation to true might help. If such option is ok to be added into the configuration of fuse, maybe I can open a PR to add it. Cc @timc1

**Comment by dubzzz** [comment]
Normally this issue should be fixed now with https://github.com/timc1/kbar/pull/350 (not released yet)
