### ISSUE TITLE
Search doesn't clear when changing currentRootActionId in the latest version

### ISSUE THREAD

**Issue by lauri865** [timc1/kbar#342]
Steps to reproduce:
1. https://kbar.vercel.app/
2. CMD+K
3. Write: "search"
4. Select "Search Docs"
5. Search input still says "search"

**Comment by cmonnom** [comment]
And backspace to delete the input will take the user back one level up.

To search within the list of doc actions, the user has to select the input then type to replace it (don't hit backspace). Then it seems we're back to the expected behavior of searching the doc actions.

**Comment by osszoi** [comment]
I'm having same issue

**Comment by nagirrab** [comment]
I also experienced this so made a quick PR to fix it: https://github.com/timc1/kbar/pull/378
