### ISSUE TITLE
Bug: Backspace keyboard event being received by pages

### ISSUE THREAD

**Issue by grahamlangford** [timc1/kbar#343]
We've noticed that the `Backspace` keyboard event is propagating up from `KBarSearch` in some instances. So far we've only noticed the behavior on Notion. 

* Possibly related to https://github.com/timc1/kbar/pull/338
* Noticed on https://www.notion.so/

**Comment by fregante** [comment]
It's because kbar captures and stops the propagation of `keypress`, but doesn't handle `keydown`, which is what Notion uses for the backspace
