### ISSUE TITLE
Documentation for parent elements and sub-search

### ISSUE THREAD

**Issue by jdross** [timc1/kbar#353]
It would be great to get some documentation for how you did the "search documents... " K-bar menu in your implementation on the vercel site.

It would also be helpful if you didn't minify your site code, so we could see from your implementation!

**Comment by npfitz** [comment]
If you want to check out the source code, I believe it's in the repo under [example/src](https://github.com/timc1/kbar/tree/main/example/src). There is a `useDocsActions` hook that might prove helpful
