### ISSUE TITLE
Next.js 14 App router layout.tsx: Fails to spawn the command palette

### ISSUE THREAD

**Issue by Aymericr** [timc1/kbar#358]
Fails to spawn the command palette.
I tried wrapping it into a 'use client' component but the issue keeps happening.

Dependencies:
* Next.js 14.2.3
* React 18

```
Error: Invariant failed: Input ref is undefined, make sure you attach `query.inputRefSetter` to your search input.

Call Stack
invariant
node_modules/tiny-invariant/dist/tiny-invariant.cjs.js (14:1)
Object.getInput
node_modules/kbar/lib/useStore.js (107:1)
handler
node_modules/kbar/lib/InternalEvents.js (277:1)
```

![CleanShot 2024-05-01 at 11 53 48@2x](https://github.com/timc1/kbar/assets/4444492/015f8512-e189-40fa-82ad-8b630d68752a)

**Comment by 0x33dm** [comment]
did you manage to solve this?

**Comment by 0x33dm** [comment]
For me adding `use client` at the top of the provider ( which is them added to my root layout ) is yielding another error.

```ts
// KBarProvider.ts

'use client'

import {
  KBarAnimator,
  KBarPortal,
  KBarPositioner,
  KBarProvider as OriginalKBarProvider,
  KBarSearch
} from 'kbar'
import type { ReactNode } from 'react'

interface Props {
  children: ReactNode
}

const KBarProvider = ({ children }: Props) => {
  return (
    <OriginalKBarProvider>
      <KBarPortal>
        <KBarPositioner>
          <KBarAnimator>
            <KBarSearch />
            {/* <KBarResults /> */}
          </KBarAnimator>
        </KBarPositioner>
      </KBarPortal>
      {children}
    </OriginalKBarProvider>
  )
}

export default KBarProvider
```

The error i get is:

> [!caution]
> TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
