### ISSUE TITLE
Actions with parent proporty get added twice.

### ISSUE THREAD

**Issue by fdennig** [timc1/kbar#359]
all actions that have a parent and get registered with useRegisterActions get added twice as children of the parent action
this does NOT happen when I pass an action with a parent to the initial list of global actions.

my problem with this, is that the actions with parents that are added dynamically, get rendered twice.

has anyone else faced this problem? any suggested solutions?

help is much appreciated!

**Comment by dflantz** [comment]
bump! does anyone have a solution to this?
