### ISSUE TITLE
Load Asynchronous Actions

### ISSUE THREAD

**Issue by austincondiff** [timc1/kbar#37]
We could have some actions immediately available and additional actions would be appended after a promise is resolved (or several promises for that matter). A dev defined loading indicator could optionally be displayed in the interim.

**Comment by tommoor** [comment]
Check out the [useRegisterActions](https://github.com/timc1/kbar/blob/a7e9d84df1482f3cb22ffc772f55e9f42d53d888/example/src/Blog.tsx#L5-L20) hook, it will now allow you to register actions at any point in your application within the Provider scope.
