### ISSUE TITLE
Allow specifying regex matches instead of strict keywords

### ISSUE THREAD

**Issue by aarohmankad** [timc1/kbar#50]
I have an application (dashboard.plaid.com), where we would like to display some search results if the query matches a certain regex. From what I can tell, this isn't currently supported but could be a useful feature!

**Comment by timc1** [comment]
Hey @aarohmankad thanks for the issue!

There's going to be a bit of cleanup work around the `useMatches` hook – specifically, after working on #49, I think it's time to extract the search results into a separate hook, say, `useResults`.

Something simple like:

```
const { results } = useResults();
```

wherein `useResults` can hook into `useKBar` and coordinate all the necessary logic to return the list of results. I'll take a look later today/tomorrow to see if we can get it in ASAP 👍

**Comment by timc1** [comment]
https://github.com/timc1/kbar/pull/52
