### ISSUE TITLE
Allow Developers to Configure Keyboard Shortcut (Instead of Cmd+K)

### ISSUE THREAD

**Issue by austincondiff** [timc1/kbar#55]
It may be nice to allow developers to pass in their own custom keyboard shortcut to instantiate kbar if they didn't want to use the preconfigured cmd+k. Some apps for example use cmd+/. Others use cmd+shift+P.

**Comment by austincondiff** [comment]
Maybe even allow the possibility for it to be programmatically be instantiated as well. This would allow a button, for example, to open the search.

**Comment by avigoldman** [comment]
This would be great to have! Maybe we could use https://github.com/jamiebuilds/tinykeys to avoid having to parse the desired config? The default in that case would be `$mod+K`

**Comment by timc1** [comment]
> Maybe even allow the possibility for it to be programmatically be instantiated as well. This would allow a button, for example, to open the search.

This can be done though `query.toggle`: https://github.com/timc1/kbar/issues/118

**Comment by mpalmisano** [comment]
Hi there!  Was curious on the status of this issue.  Is this still being actively worked on?  Any way that I can plug in?  I was wanting to use this in a project but Cmd+K conflicts with another shortcut we have.

**Comment by timc1** [comment]
Hey @mpalmisano! What shortcut does Cmd+K trigger on your site?

**Comment by mpalmisano** [comment]
@timc1 Our doc editor has a Cmd+K feature to access editor specific shortcuts and tooling.  I built a more general Cmd+K mostly navigation shortcut box using kbar.  I could try to get them to change their shortcut but users are already used to it so I was thinking updating mine is better.

**Comment by jimthedev** [comment]
I don't know if anyone has seen this but Chrome on Windows now has a Ctrl-K shortcut on windows that opens a google search so the ability to configure or at least an example of how to disable the default binding is probably a good idea..

**Comment by jimthedev** [comment]
Tagging @timc1 here because I think the fact that Chromes new shortcut could break kbar is probably worth discussing.

**Comment by timc1** [comment]
Looks like there's enough of an ask for this – let's do it :-)
