### ISSUE TITLE
Why wrap our entire app with KBarProvider?

### ISSUE THREAD

**Issue by pdrbrnd** [timc1/kbar#61]
Hi there! First of all, thanks for this :)

I it really necessary to wrap our app with your context provider?
From what I can tell, only `KBar` components actually need to access that context. There are no other exports (like custom hooks) that we can use anywhere else in our app (that would require the provider) – and, honestly, I don't see a use-case where that would be necessary.

If I'm not completely mistaken, this would just require an update to the docs.

**Comment by timc1** [comment]
Hey! You don't need to per se, however for simplicity sake if you wanted to add a button somewhere in your app that triggered kbar, that's where having access to `useKBar` would be needed.

Additionally, it's good to know that state updates within kbar only re render components who's `useKBar` value changed, so there are no performance hits to wrapping this provider around your entire app.
