### ISSUE TITLE
Add action priority / ordering

### ISSUE THREAD

**Issue by tommoor** [timc1/kbar#66]
When using `useRegisterActions` to dynamically add actions while components are mounted it's difficult to predict which order items will appear in, adding an optional `priority` attribute to actions would put control of this in the developers hands while handling the boilerplate of sorting internally.

**Comment by leeoocca** [comment]
This would be very useful.

For example adding contextual actions to the top would allow the user to discover them more easily. Right now they are "hidden" at the bottom of the list.

**Comment by smhutch** [comment]
This would be super, super helpful. Another consideration here is that "groups" of results should perhaps be sorted first, then results within that group sorted afterwards.

Happy to help contribute towards development of this in January.

**Comment by CryogenicPlanet** [comment]
Any updates on this?

**Comment by phuctm97** [comment]
> This would be very useful.
> 
> For example adding contextual actions to the top would allow the user to discover them more easily. Right now they are "hidden" at the bottom of the list.

Second this, current workaround to there is only 1 `useRegisterActions`, no default actions, all actions are re-registered when there are changes, this way the order can be predictable. But an API that supports this internally makes a lot of sense and will be very helpful!

**Comment by devenbhooshan** [comment]
+1 
this would be very useful. 



I think these are the places where changes needed to be added


`Action` type needs to have a `priority` field of type int in `src/types.ts`

and that priority needs to be taken into account  in `src/useMatches.tsx`
```
const results = React.useMemo(() => {

      //...
      for (let i = 0; i < actions.length; i++) {
        results.push(actions[i]);
      }
    });
    //

    return results;
  }, [matches]);
```


@timc1 let me know if this looks correct. I can help with the PR.

**Comment by timc1** [comment]
Hey @devenbhooshan! Thanks for the offer – if you want to give it a shot, by all means! I would look into alternative solutions as a starting point, like [command-score](https://github.com/superhuman/command-score).

**Comment by TaylorFacen** [comment]
+1 this would be super helpful for me as well
