### ISSUE TITLE
KBar doesn't work in final build

### ISSUE THREAD

**Issue by WhoAdarshPandya** [timc1/kbar#85]
hey tim! Awsome work with  the Kbar, i've been using it in my preact app - in dev mode it works fine but after production build it doesn't work. consider me a noob trying to solve things. 

it shows something like this in console 

```
vendor.822cbe4a.js:29 Uncaught TypeError: (0 , Zt.default) is not a function
    at Gf (vendor.822cbe4a.js:29)
    at Y.qf [as constructor] (vendor.822cbe4a.js:29)
    at Y.Ho [as render] (vendor.822cbe4a.js:1)
    at dr (vendor.822cbe4a.js:1)
    at ti (vendor.822cbe4a.js:1)
    at dr (vendor.822cbe4a.js:1)
    at ti (vendor.822cbe4a.js:1)
    at dr (vendor.822cbe4a.js:1)
    at ti (vendor.822cbe4a.js:1)
    at dr (vendor.822cbe4a.js:1)
Gf @ vendor.822cbe4a.js:29
qf @ vendor.822cbe4a.js:29
Ho @ vendor.822cbe4a.js:1
dr @ vendor.822cbe4a.js:1
ti @ vendor.822cbe4a.js:1
dr @ vendor.822cbe4a.js:1
ti @ vendor.822cbe4a.js:1
dr @ vendor.822cbe4a.js:1
ti @ vendor.822cbe4a.js:1
dr @ vendor.822cbe4a.js:1
Ie @ vendor.822cbe4a.js:1
(anonymous) @ index.dc5496f6.js:formatted:113
```

in index.js (pretty-printed) it highlights this portion
```
y(i(r.KBarProvider, {
    actions: S,
    children: [o(r.KBarPortal, {
        children: o(r.KBarPositioner, {
            children: i(r.KBarAnimator, {
                style: B,
                children: [o(r.KBarSearch, {
                    style: k,
                    placeholder: "Type a command or search\u2026"
                }), o(r.KBarResults, {})]
            })
        })
    }), o(g, {
        children: o(v, {})
    })]
}), document.getElementById("app"));
```
it'd be really great if you can help me with this. thanks in advance

**Comment by kxxoling** [comment]
> hey @timc1 , Thanks for reply, i guess problem comes when we try to bundle it with vite! webpack works fine with Kbar

@WhoAdarshPandya How you fixed this issue finally? Replacing vite with webpack?

**Comment by WhoAdarshPandya** [comment]
> > hey @timc1 , Thanks for reply, i guess problem comes when we try to bundle it with vite! webpack works fine with Kbar
> 
> @WhoAdarshPandya How you fixed this issue finally? Replacing vite with webpack?

not yet fixed, even I can't find what causes error because it works perfect in dev mode. can't replace vite for webpack which is laggy and slow compared to vite

**Comment by evcohen** [comment]
im seeing this error too with a vite build ...looks like the trace is pointing to:

```
var _c = (0, useKBar_1.default)(function (state) { return ({
        visualState: state.visualState,
        showing: state.visualState !== types_1.VisualState.hidden,
    }); }), query = _c.query, options = _c.options, visualState = _c.visualState, showing = _c.showing;
```

 `useToggleHandler` in `InternalEvents.js`; am getting `useKBar_1.default is not a function`. unsure why though

**Comment by timc1** [comment]
Will be reworking the imports in an upcoming PR which might fix this, or help us narrow down the issue.

**Comment by evcohen** [comment]
thanks — I can test the branch on my build when it’s posted!

**Comment by kevinhu** [comment]
I had this issue as well, and it seems that Vite is unhappy about the default export syntax applied to a function. If you switch it to a named export, the build error goes away: https://github.com/timc1/kbar/pull/131

**Comment by timc1** [comment]
This should be resolved in the [latest release](https://github.com/timc1/kbar/releases/tag/v0.1.0-beta.23) – thank you @kevinhu!

**Comment by evcohen** [comment]
thanks @kevinhu and @timc1 💯
